var searchData=
[
  ['queries_0',['queries',['../cola-indexes-and-mapped-queries.html',1,'COLA indexes and mapped queries'],['../cold-exception-paths-in-complete-queries.html',1,'Cold exception paths in complete queries'],['../md_docs_2implementation.html#complete-encoded-chain-queries',1,'Complete encoded-chain queries'],['../md_bench_2query__chain.html',1,'Complete prepared-chain queries']]],
  ['queries_20after_20bit_20arithmetic_20cleanup_1',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['queries_20after_20the_20rank_20and_20elias–fano_20refactor_2',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['queries_20and_20their_20separate_20costs_3',['Construction, queries, and their separate costs',['../md_docs_2design.html#construction-queries-and-their-separate-costs',1,'']]],
  ['queries_20with_20absolute_20block_20prefixes_4',['Complete queries with absolute block prefixes',['../complete-queries-with-absolute-block-prefixes.html',1,'']]],
  ['queries_20with_20comparison_20state_5',['Complete queries with comparison state',['../md_bench_2query__compare.html',1,'']]],
  ['queries_20with_20shared_20navigation_20views_6',['Owning queries with shared navigation views',['../md_bench_2shared__query.html',1,'']]],
  ['query_7',['query',['../md_docs_2design.html#a-comparison-belongs-to-one-query',1,'A comparison belongs to one query'],['../structdiet_1_1profile__query__context.html#a84d1d50190e93046773f940d1148781e',1,'diet::profile_query_context::query()']]],
  ['query_20a_20blob_8',['Build and query a blob',['../index.html#build-and-query-a-blob',1,'']]],
  ['query_20bounds_20and_20scheduling_20obligations_9',['3. Query bounds and scheduling obligations',['../md_docs_2network-admission.html#autotoc_md3-query-bounds-and-scheduling-obligations',1,'']]],
  ['query_20chains_10',['Portable sections and mapped query chains',['../md_docs_2implementation.html#portable-sections-and-mapped-query-chains',1,'']]],
  ['query_20collateral_20and_20correctness_11',['Query collateral and correctness',['../cola-comparison-layout.html#query-collateral-and-correctness',1,'']]],
  ['query_20comparison_12',['Final complete-query comparison',['../complete-queries-with-absolute-block-prefixes.html#final-complete-query-comparison',1,'']]],
  ['query_20results_13',['query results',['../md_bench_2query__rounding.html#query-results-1',1,'Query results'],['../complete-queries-after-the-rank-and-eliasfano-refactor.html#query-results',1,'Query results']]],
  ['query_20roots_14',['Mapped blobs and exact query roots',['../mapped-blobs-and-exact-query-roots.html',1,'']]],
  ['query_20the_20whole_20chain_15',['Query the whole chain',['../index.html#query-the-whole-chain',1,'']]],
  ['query_2eh_16',['query.h',['../query_8h.html',1,'']]],
  ['query_2emd_17',['query.md',['../query_8md.html',1,'']]],
  ['query_5f_18',['query_',['../structdiet_1_1profile__query__context.html#a46d2eb6a3dc262acacba15f70fe99866',1,'diet::profile_query_context']]],
  ['query_5fabsolute_2emd_19',['query_absolute.md',['../query__absolute_8md.html',1,'']]],
  ['query_5fchain_2emd_20',['query_chain.md',['../query__chain_8md.html',1,'']]],
  ['query_5fcompare_2emd_21',['query_compare.md',['../query__compare_8md.html',1,'']]],
  ['query_5fcontext_22',['query_context',['../structdiet_1_1fridge.html#ab2684c1b4ea38b0b46f6742ddc69e9ba',1,'diet::fridge']]],
  ['query_5fcursor_23',['query_cursor',['../structdiet_1_1query__cursor.html',1,'diet::query_cursor&lt; P, Blob &gt;'],['../structdiet_1_1fridge.html#a9009ab50fbae24d911b6516068797b71',1,'diet::fridge::query_cursor'],['../structdiet_1_1query__cursor.html#aaca6d896320cf68bce59d2005a1a28f6',1,'diet::query_cursor::query_cursor()']]],
  ['query_5ferrors_2emd_24',['query_errors.md',['../query__errors_8md.html',1,'']]],
  ['query_5fmatch_25',['query_match',['../structdiet_1_1query__match.html',1,'diet']]],
  ['query_5frefactor_2emd_26',['query_refactor.md',['../query__refactor_8md.html',1,'']]],
  ['query_5froot_27',['query_root',['../structdiet_1_1query__root.html#a713d901bc5f3669a3b85029418f6eb82',1,'diet::query_root::query_root()'],['../structdiet_1_1fridge.html#a98c137f35fd30a68fbee32da4b4007e3',1,'diet::fridge::query_root'],['../structdiet_1_1query__root.html',1,'diet::query_root&lt; P, Blob &gt;']]],
  ['query_5froot_5fbuilder_28',['query_root_builder',['../structdiet_1_1query__root__builder.html#afd4615abb6116b922e75484cf09a9561',1,'diet::query_root_builder::query_root_builder()'],['../structdiet_1_1fridge.html#ab85a90b66636b2c9ebbbabb136e3dcf9',1,'diet::fridge::query_root_builder'],['../structdiet_1_1query__root__builder.html#a8d59f970b32d27bec4893b5fe0d4dd51',1,'diet::query_root_builder::query_root_builder(query_root_builder const &amp;)=delete'],['../structdiet_1_1query__root__builder.html#aabadfd5254818a651c98daba33e4b78c',1,'diet::query_root_builder::query_root_builder(query_root_builder &amp;&amp;)=default'],['../structdiet_1_1query__root__builder.html',1,'diet::query_root_builder&lt; P &gt;']]],
  ['query_5froot_5fbuilder_3c_20p_20_3e_29',['query_root_builder&lt; P &gt;',['../structdiet_1_1query__root.html#a9dbfd85b6556d32ab1a3af443d0cec74',1,'diet::query_root']]],
  ['query_5frounding_2emd_30',['query_rounding.md',['../query__rounding_8md.html',1,'']]],
  ['querying_20an_20immutable_20catalog_20chain_31',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['queue_20actually_20finishes_32',['5. Why the replay queue actually finishes',['../md_docs_2rebuild.html#autotoc_md5-why-the-replay-queue-actually-finishes',1,'']]]
];
