var searchData=
[
  ['i_20measured_0',['i measured',['../md_bench_2neon__cult__rank.html#what-i-measured',1,'What I measured'],['../packed-group-and-bitmap-rank-reductions.html#what-i-measured-1',1,'What I measured']]],
  ['id_1',['id',['../structeverett_1_1parsed__object__path.html#adb896aa9bfd684217fba97177d8c9261',1,'everett::parsed_object_path']]],
  ['identity_2',['identity',['../structeverett_1_1merge__checkpoint.html#aabbbddec4dae8efc039036be08bfc69d',1,'everett::merge_checkpoint::identity'],['../md_docs_2file-lifecycle.html#path-spelling-and-content-identity',1,'Path spelling and content identity']]],
  ['identity_20and_20multiplicity_3',['Logical key identity and multiplicity',['../md_docs_2arrows.html#logical-key-identity-and-multiplicity',1,'']]],
  ['identity_20and_20order_4',['1. One canonical identity and order',['../md_docs_2keys.html#autotoc_md1-one-canonical-identity-and-order',1,'']]],
  ['identity_5f_5',['identity_',['../structeverett_1_1merge__publication.html#a53326bbc51355aa718a87d2256dbc3ca',1,'everett::merge_publication']]],
  ['illustration_20not_20a_20wire_20format_6',['3. A framing illustration, not a wire format',['../md_docs_2keys.html#autotoc_md3-a-framing-illustration-not-a-wire-format',1,'']]],
  ['immutable_20catalog_20chain_7',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['implementation_8',['Bounded first implementation',['../md_docs_2durability.html#bounded-first-implementation',1,'']]],
  ['implementation_20assignments_9',['Next implementation assignments',['../md_docs_2implementation.html#next-implementation-assignments',1,'']]],
  ['implementation_20boundary_10',['Pins integration and implementation boundary',['../md_docs_2durability.html#pins-integration-and-implementation-boundary',1,'']]],
  ['implementation_20boundary_20and_20checks_11',['9. Implementation boundary and checks',['../md_docs_2keys.html#autotoc_md9-implementation-boundary-and-checks',1,'']]],
  ['implementation_20boundary_20and_20next_20contract_12',['7. Implementation boundary and next contract',['../md_docs_2arrows.html#autotoc_md7-implementation-boundary-and-next-contract',1,'']]],
  ['implementation_20status_13',['Everett implementation status',['../md_docs_2implementation.html',1,'']]],
  ['implementation_2emd_14',['implementation.md',['../implementation_8md.html',1,'']]],
  ['implementations_15',['The implementations',['../packed-group-and-bitmap-rank-reductions.html#the-implementations',1,'']]],
  ['implemented_20foundations_16',['Implemented foundations',['../md_docs_2implementation.html#implemented-foundations',1,'']]],
  ['in_20a_20category_20chosen_20per_20key_17',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['incoming_5f_18',['incoming_',['../structeverett_1_1index__builder.html#ae36f87485f846b5680bc0d53be0b3108',1,'everett::index_builder']]],
  ['incoming_5fdecoder_5f_19',['incoming_decoder_',['../structeverett_1_1index__builder.html#ace594e2aa60e54a25789ff4c183c9025',1,'everett::index_builder']]],
  ['incoming_5ffalse_5f_20',['incoming_false_',['../structeverett_1_1index__builder.html#a125ed372f352be86817d604994daac82',1,'everett::index_builder']]],
  ['incremental_20rebuilding_21',['Strong deletion by incremental rebuilding',['../md_docs_2rebuild.html',1,'']]],
  ['independence_20is_20componentwise_20composition_22',['3. Partition independence is componentwise composition',['../md_docs_2arrows.html#autotoc_md3-partition-independence-is-componentwise-composition',1,'']]],
  ['index_20repair_23',['5. Native-preserving index repair',['../md_docs_2sampling.html#autotoc_md5-native-preserving-index-repair',1,'']]],
  ['index_5fbuilder_24',['index_builder',['../structeverett_1_1index__builder.html',1,'everett::index_builder&lt; P &gt;'],['../structeverett_1_1index__builder.html#a56ba108d9662573e74bd301893b4a376',1,'everett::index_builder::index_builder(blob_type const &amp;source)'],['../structeverett_1_1index__builder.html#a063a2d77bbdebdc02a438c7a457cad06',1,'everett::index_builder::index_builder(index_builder &amp;&amp;)=default'],['../structeverett_1_1index__builder.html#a45202aee52c1b81580ebd789a6b62020',1,'everett::index_builder::index_builder(index_builder const &amp;)=delete']]],
  ['index_5fbuilder_2eh_25',['index_builder.h',['../index__builder_8h.html',1,'']]],
  ['index_5fbuilder_3c_20p_20_3e_26',['index_builder&lt; P &gt;',['../structeverett_1_1profile__blob.html#a66cfd51913f990b9213d9dcf763400e8',1,'everett::profile_blob']]],
  ['index_5fpipeline_27',['index_pipeline',['../structeverett_1_1index__pipeline.html',1,'everett::index_pipeline&lt; P &gt;'],['../structeverett_1_1index__pipeline.html#a0b33348b39eaded901c1b150b8ebf958',1,'everett::index_pipeline::index_pipeline(pair_type target, std::vector&lt; pair_type &gt; native_stages)'],['../structeverett_1_1index__pipeline.html#a91c3bc12011e6f1e996a0f711f1584f6',1,'everett::index_pipeline::index_pipeline(index_pipeline const &amp;)=delete'],['../structeverett_1_1index__pipeline.html#a0266b8373f4605b5c38f9448671d05fb',1,'everett::index_pipeline::index_pipeline(index_pipeline &amp;&amp;)=default']]],
  ['index_5fpipeline_2eh_28',['index_pipeline.h',['../index__pipeline_8h.html',1,'']]],
  ['indexing_29',['Fractional indexing',['../everett-an-abstract-proof-core.html#fractional-indexing',1,'']]],
  ['information_30',['information',['../everett-an-abstract-proof-core.html#contact-information-1',1,'Contact Information'],['../index.html#contact-information',1,'Contact Information']]],
  ['ingestion_20state_20and_20published_20state_31',['5. Ingestion state and published state',['../md_docs_2network-admission.html#autotoc_md5-ingestion-state-and-published-state',1,'']]],
  ['initial_5fmetadata_32',['initial_metadata',['../namespaceeverett_1_1profile__detail.html#a1c9184884c42b7cda3e38b32dcac1a9c',1,'everett::profile_detail']]],
  ['input_20and_20results_33',['Shared input and results',['../md_bench_2rank__compare__windows.html#shared-input-and-results',1,'']]],
  ['input_5fclosed_5f_34',['input_closed_',['../structeverett_1_1index__builder.html#ac82308103eac1d797d711acf18a0a97b',1,'everett::index_builder']]],
  ['input_5fmode_35',['input_mode',['../structeverett_1_1index__builder.html#af55408e8f8b798f037a217f1b559d69a',1,'everett::index_builder']]],
  ['input_5fmode_5f_36',['input_mode_',['../structeverett_1_1index__builder.html#ab3fe9781ce2a615c65f126990a58b90f',1,'everett::index_builder']]],
  ['input_5fversion_37',['input_version',['../structeverett_1_1merge__input__cursor.html#a51169797e48931ce70f53e3b0c947e2d',1,'everett::merge_input_cursor']]],
  ['input_5fversions_38',['input_versions',['../structeverett_1_1merge__identity.html#a9c862187aa3631f77f1c04c880af70b9',1,'everett::merge_identity']]],
  ['inputs_39',['inputs',['../structeverett_1_1merge__checkpoint.html#a0ad4cc4dec37a82a9f0b01b64bf7f583',1,'everett::merge_checkpoint']]],
  ['inputs_20and_20checks_40',['Inputs and checks',['../blob-and-pipeline-performance.html#inputs-and-checks',1,'']]],
  ['inputs_20and_20commands_41',['Pinned inputs and commands',['../md_bench_2rank__compare__windows.html#pinned-inputs-and-commands',1,'']]],
  ['integration_20and_20implementation_20boundary_42',['Pins integration and implementation boundary',['../md_docs_2durability.html#pins-integration-and-implementation-boundary',1,'']]],
  ['interleave_43',['interleave',['../structeverett_1_1profile__blob.html#aff3a18038a5876e522f09185ccc050e5',1,'everett::profile_blob']]],
  ['interleave_5f_44',['interleave_',['../structeverett_1_1profile__blob.html#ab54f2b7f18ad04320525cfcc13f96e0f',1,'everett::profile_blob']]],
  ['interpretation_20with_20the_20data_45',['8. Pin interpretation with the data',['../md_docs_2keys.html#autotoc_md8-pin-interpretation-with-the-data',1,'']]],
  ['is_20called_20durable_46',['9. Acceptance before the backend is called durable',['../md_docs_2catalog.html#autotoc_md9-acceptance-before-the-backend-is-called-durable',1,'']]],
  ['is_20componentwise_20composition_47',['3. Partition independence is componentwise composition',['../md_docs_2arrows.html#autotoc_md3-partition-independence-is-componentwise-composition',1,'']]],
  ['is_20measured_48',['What is measured',['../md_bench_2key__bits.html#what-is-measured',1,'']]],
  ['is_20not_20a_20byte_20bound_49',['4. Entry accounting is not a byte bound',['../md_docs_2network-admission.html#autotoc_md4-entry-accounting-is-not-a-byte-bound',1,'']]]
];
