var searchData=
[
  ['what_20can_20be_20adopted_20directly_0',['1. What can be adopted directly',['../md_docs_2network-admission.html#autotoc_md1-what-can-be-adopted-directly',1,'']]],
  ['what_20i_20measured_1',['what i measured',['../packed-group-and-bitmap-rank-reductions.html#what-i-measured-1',1,'What I measured'],['../md_bench_2neon__cult__rank.html#what-i-measured',1,'What I measured']]],
  ['what_20is_20measured_2',['What is measured',['../md_bench_2key__bits.html#what-is-measured',1,'']]],
  ['what_20strong_20deletion_20promises_20here_3',['2. What strong deletion promises here',['../md_docs_2rebuild.html#autotoc_md2-what-strong-deletion-promises-here',1,'']]],
  ['what_20the_20assumptions_20mean_4',['What the assumptions mean',['../everett-an-abstract-proof-core.html#what-the-assumptions-mean',1,'']]],
  ['what_20the_20catalog_20owns_5',['1. What the catalog owns',['../md_docs_2catalog.html#autotoc_md1-what-the-catalog-owns',1,'']]],
  ['what_20the_20check_20establishes_6',['What the check establishes',['../md_docs_2doxygen.html#what-the-check-establishes',1,'']]],
  ['what_20the_20critical_20value_20means_7',['What the critical value means',['../md_docs_2sampling.html#what-the-critical-value-means',1,'']]],
  ['what_20the_20variants_20measure_8',['What the variants measure',['../md_bench_2rank__compare.html#what-the-variants-measure',1,'']]],
  ['what_20to_20retain_20from_20leveldb_20s_20lifecycle_9',['What to retain from LevelDB&apos;s lifecycle',['../md_docs_2file-lifecycle.html#what-to-retain-from-leveldbs-lifecycle',1,'']]],
  ['where_20the_20chain_20proof_20stops_10',['6. Where the chain proof stops',['../md_docs_2sampling.html#autotoc_md6-where-the-chain-proof-stops',1,'']]],
  ['while_20retaining_20native_20allocations_11',['Build a chain while retaining native allocations',['../index.html#build-a-chain-while-retaining-native-allocations',1,'']]],
  ['while_20the_20foreground_20remains_20available_12',['Replay while the foreground remains available',['../md_docs_2rebuild.html#replay-while-the-foreground-remains-available',1,'']]],
  ['whole_20chain_13',['Query the whole chain',['../index.html#query-the-whole-chain',1,'']]],
  ['why_20a_20local_20window_20works_20for_20k_203_14',['2. Why a local window works for K = 3',['../md_docs_2sampling.html#autotoc_md2-why-a-local-window-works-for-k--3',1,'']]],
  ['why_20catch_20up_20finishes_15',['Why catch-up finishes',['../md_docs_2design.html#why-catch-up-finishes',1,'']]],
  ['why_20failure_20changes_20the_20protocol_16',['Why failure changes the protocol',['../md_docs_2durability.html#why-failure-changes-the-protocol',1,'']]],
  ['why_20historical_20updates_20stop_20determining_20the_20universe_17',['6. Why historical updates stop determining the universe',['../md_docs_2rebuild.html#autotoc_md6-why-historical-updates-stop-determining-the-universe',1,'']]],
  ['why_20the_20replay_20queue_20actually_20finishes_18',['5. Why the replay queue actually finishes',['../md_docs_2rebuild.html#autotoc_md5-why-the-replay-queue-actually-finishes',1,'']]],
  ['width_19',['width',['../structeverett_1_1policy__detail_1_1value__traits_3_01fixed__values_3_01_n_01_4_01_4.html#a6ed46c18569158d4a084f85ebb284d7c',1,'everett::policy_detail::value_traits&lt; fixed_values&lt; N &gt; &gt;::width'],['../structeverett_1_1fixed__values.html#a1134ad906e42f7dadc942794c88c29d8',1,'everett::fixed_values::width'],['../structeverett_1_1policy__detail_1_1value__traits_3_01variable__values_01_4.html#aab2af34e4203d9416769cb7b4b4b8e01',1,'everett::policy_detail::value_traits&lt; variable_values &gt;::width']]],
  ['width_20values_20',['select15 and fixed-width values',['../md_docs_2design.html#select15-and-fixed-width-values',1,'']]],
  ['window_21',['Preparing the first window',['../md_docs_2query.html#preparing-the-first-window',1,'']]],
  ['window_20works_20for_20k_203_22',['2. Why a local window works for K = 3',['../md_docs_2sampling.html#autotoc_md2-why-a-local-window-works-for-k--3',1,'']]],
  ['windows_20packed_20rank_20comparison_23',['Native Windows packed-rank comparison',['../md_bench_2rank__compare__windows.html',1,'']]],
  ['wire_20format_24',['3. A framing illustration, not a wire format',['../md_docs_2keys.html#autotoc_md3-a-framing-illustration-not-a-wire-format',1,'']]],
  ['with_20existing_20sql_20tools_25',['8. Browse with existing SQL tools',['../md_docs_2catalog.html#autotoc_md8-browse-with-existing-sql-tools',1,'']]],
  ['with_20the_20data_26',['8. Pin interpretation with the data',['../md_docs_2keys.html#autotoc_md8-pin-interpretation-with-the-data',1,'']]],
  ['words_27',['words',['../namespaceeverett_1_1select__groups__detail.html#a0b637072b36d0ab89afdc0d1ecb902aa',1,'everett::select_groups_detail::words()'],['../structeverett_1_1rank__index.html#ac20147a9edf87c874dbc0b7085b2f26e',1,'everett::rank_index::words'],['../namespaceeverett_1_1select15__detail.html#a17fb86409dd19adf5be155319635f64c',1,'everett::select15_detail::words()']]],
  ['words_5f_28',['words_',['../structeverett_1_1rank__view.html#a58fbb7f0f6b2f04a6e7e943f9c66b86d',1,'everett::rank_view']]],
  ['work_29',['work',['../md_docs_2sampling.html#autotoc_md4-space-and-scan-work',1,'4. Space and scan work'],['../md_docs_2design.html#autotoc_md5-redundant-levels-and-merge-work',1,'5. Redundant levels and merge work'],['../md_docs_2design.html#autotoc_md6-snapshots-saves-and-shared-work',1,'6. Snapshots, saves, and shared work'],['../md_docs_2sampling.html#autotoc_md7-executable-evidence-and-remaining-proof-work',1,'7. Executable evidence and remaining proof work'],['../md_docs_2catalog.html#operations-and-background-work',1,'Operations and background work'],['../md_docs_2catalog.html',1,'SQLite catalog for worlds, pins and background work']]],
  ['work_20and_20ownership_20bounds_30',['Work and ownership bounds',['../md_docs_2query.html#work-and-ownership-bounds',1,'']]],
  ['work_20and_20verification_31',['Work and verification',['../md__a_g_e_n_t_s.html#work-and-verification',1,'']]],
  ['work_20that_20can_20stop_20and_20resume_32',['Work that can stop and resume',['../index.html#work-that-can-stop-and-resume',1,'']]],
  ['work_5f_33',['work_',['../structeverett_1_1sample__cursor.html#a3d62160a3d2ecb90c64f71948f47a9ea',1,'everett::sample_cursor']]],
  ['works_20for_20k_203_34',['2. Why a local window works for K = 3',['../md_docs_2sampling.html#autotoc_md2-why-a-local-window-works-for-k--3',1,'']]],
  ['world_35',['world',['../structeverett_1_1world.html',1,'everett::world&lt; P &gt;'],['../structeverett_1_1multiverse.html#a413dfd9ca6d18e74eb0a3c21fe3e62a6',1,'everett::multiverse::world'],['../structeverett_1_1partition__round.html#ad5239405300e13d7c2b55951317bb7fc',1,'everett::partition_round::world']]],
  ['world_20and_20apply_20disjoint_20updates_36',['Fork a world and apply disjoint updates',['../index.html#fork-a-world-and-apply-disjoint-updates',1,'']]],
  ['world_20rounds_37',['9. Partitioned world rounds',['../md_docs_2design.html#autotoc_md9-partitioned-world-rounds',1,'']]],
  ['world_20semantics_20and_20algebra_38',['World semantics and algebra',['../md_docs_2implementation.html#world-semantics-and-algebra',1,'']]],
  ['world_2eh_39',['world.h',['../world_8h.html',1,'']]],
  ['world_5fapply_5fresult_40',['world_apply_result',['../namespaceeverett.html#abdd0012244f6054f1fd40fe06a2f3a0b',1,'everett']]],
  ['world_5fbatch_41',['world_batch',['../structeverett_1_1world__batch.html',1,'everett']]],
  ['world_5fedit_42',['world_edit',['../structeverett_1_1world__edit.html',1,'everett']]],
  ['world_5fimport_5flimits_43',['world_import_limits',['../structeverett_1_1world__import__limits.html',1,'everett']]],
  ['world_5frecord_44',['world_record',['../structeverett_1_1world__record.html',1,'everett']]],
  ['world_5frun_45',['world_run',['../structeverett_1_1world__run.html#adcacec70aaf82ce880f7a05fd6316c57',1,'everett::world_run::world_run()'],['../structeverett_1_1world__run.html',1,'everett::world_run&lt; V &gt;']]],
  ['worlds_20and_20ownership_46',['Blobs, worlds, and ownership',['../index.html#blobs-worlds-and-ownership',1,'']]],
  ['worlds_20pins_20and_20background_20work_47',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['wrapping_5ffingerprint_5falgebra_48',['wrapping_fingerprint_algebra',['../structeverett_1_1wrapping__fingerprint__algebra.html',1,'everett']]],
  ['write_49',['write',['../structeverett_1_1u64__world__codec.html#abe9f0878570e9f3a7a47ff0caa19a673',1,'everett::u64_world_codec']]],
  ['write_5fbackspace_50',['write_backspace',['../namespaceeverett_1_1profile__detail.html#a4bff626bc2875fb4527795d51c640cb9',1,'everett::profile_detail']]],
  ['write_5fcount_51',['write_count',['../namespaceeverett_1_1profile__detail.html#a12fee97090b78ace066a89cd20b836ac',1,'everett::profile_detail']]],
  ['write_5fhigh_52',['write_high',['../namespaceeverett_1_1select__groups__detail.html#a784fd1dd9cd322fe30341b01583a8e83',1,'everett::select_groups_detail']]],
  ['write_5fu64_53',['write_u64',['../namespaceeverett_1_1world__detail.html#a3370b34fe33b8572af72cee0394858f1',1,'everett::world_detail']]],
  ['writer_54',['Verification still required for the writer',['../md_docs_2file-lifecycle.html#verification-still-required-for-the-writer',1,'']]],
  ['writer_5f_55',['writer_',['../structeverett_1_1index__builder.html#aa61123905f65d229d184dc09bd6119ad',1,'everett::index_builder']]]
];
