var searchData=
[
  ['queries_0',['queries',['../cold-exception-paths-in-complete-queries.html',1,'Cold exception paths in complete queries'],['../md_docs_2implementation.html#complete-encoded-chain-queries',1,'Complete encoded-chain queries'],['../md_bench_2query__chain.html',1,'Complete prepared-chain queries']]],
  ['queries_20after_20bit_20arithmetic_20cleanup_1',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['queries_20after_20the_20rank_20and_20elias–fano_20refactor_2',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['queries_20and_20their_20separate_20costs_3',['Construction, queries, and their separate costs',['../md_docs_2design.html#construction-queries-and-their-separate-costs',1,'']]],
  ['queries_20with_20comparison_20state_4',['Complete queries with comparison state',['../md_bench_2query__compare.html',1,'']]],
  ['queries_20with_20shared_20navigation_20views_5',['Owning queries with shared navigation views',['../md_bench_2shared__query.html',1,'']]],
  ['query_6',['query',['../md_docs_2design.html#a-comparison-belongs-to-one-query',1,'A comparison belongs to one query'],['../structeverett_1_1profile__query__context.html#aaef281ec10ccf9ffc962f7bd07c4fc50',1,'everett::profile_query_context::query()']]],
  ['query_20a_20blob_7',['Build and query a blob',['../index.html#build-and-query-a-blob',1,'']]],
  ['query_20bounds_20and_20scheduling_20obligations_8',['3. Query bounds and scheduling obligations',['../md_docs_2network-admission.html#autotoc_md3-query-bounds-and-scheduling-obligations',1,'']]],
  ['query_20chains_9',['Portable sections and mapped query chains',['../md_docs_2implementation.html#portable-sections-and-mapped-query-chains',1,'']]],
  ['query_20results_10',['query results',['../md_bench_2query__rounding.html#query-results-1',1,'Query results'],['../complete-queries-after-the-rank-and-eliasfano-refactor.html#query-results',1,'Query results']]],
  ['query_20roots_11',['Mapped blobs and exact query roots',['../mapped-blobs-and-exact-query-roots.html',1,'']]],
  ['query_20the_20whole_20chain_12',['Query the whole chain',['../index.html#query-the-whole-chain',1,'']]],
  ['query_2eh_13',['query.h',['../query_8h.html',1,'']]],
  ['query_2emd_14',['query.md',['../query_8md.html',1,'']]],
  ['query_5f_15',['query_',['../structeverett_1_1profile__query__context.html#ae19021530b0451a8e4703cb11b257e7f',1,'everett::profile_query_context']]],
  ['query_5fchain_2emd_16',['query_chain.md',['../query__chain_8md.html',1,'']]],
  ['query_5fcompare_2emd_17',['query_compare.md',['../query__compare_8md.html',1,'']]],
  ['query_5fcontext_18',['query_context',['../structeverett_1_1multiverse.html#ada610e4bf56e2d2eba2e59d3b2db17b4',1,'everett::multiverse']]],
  ['query_5fcursor_19',['query_cursor',['../structeverett_1_1query__cursor.html',1,'everett::query_cursor&lt; P, Blob &gt;'],['../structeverett_1_1multiverse.html#a4574e62ea7e8e0d570b78fabeb8af79f',1,'everett::multiverse::query_cursor'],['../structeverett_1_1query__cursor.html#a99cfc870e6d28d2f1b76b6d505641147',1,'everett::query_cursor::query_cursor()']]],
  ['query_5ferrors_2emd_20',['query_errors.md',['../query__errors_8md.html',1,'']]],
  ['query_5fmatch_21',['query_match',['../structeverett_1_1query__match.html',1,'everett']]],
  ['query_5frefactor_2emd_22',['query_refactor.md',['../query__refactor_8md.html',1,'']]],
  ['query_5froot_23',['query_root',['../structeverett_1_1query__root.html',1,'everett::query_root&lt; P, Blob &gt;'],['../structeverett_1_1query__root.html#a18a3a4bbdb6176ca58545555920370ce',1,'everett::query_root::query_root()'],['../structeverett_1_1multiverse.html#abf3d1194158b57103ac5989803f12d4a',1,'everett::multiverse::query_root']]],
  ['query_5froot_5fbuilder_24',['query_root_builder',['../structeverett_1_1query__root__builder.html#aae047dad07eb73d5a596fd4cf64f41cc',1,'everett::query_root_builder::query_root_builder()'],['../structeverett_1_1multiverse.html#adf9e6ba5e0fbd317095350e1ac7e5c01',1,'everett::multiverse::query_root_builder'],['../structeverett_1_1query__root__builder.html#aae6ae777b7fb9dfbac4b3bb86ebfdc35',1,'everett::query_root_builder::query_root_builder()'],['../structeverett_1_1query__root__builder.html',1,'everett::query_root_builder&lt; P &gt;'],['../structeverett_1_1query__root__builder.html#aff902ca670a37bc86390039389c194b4',1,'everett::query_root_builder::query_root_builder()']]],
  ['query_5froot_5fbuilder_3c_20p_20_3e_25',['query_root_builder&lt; P &gt;',['../structeverett_1_1query__root.html#a9dbfd85b6556d32ab1a3af443d0cec74',1,'everett::query_root']]],
  ['query_5frounding_2emd_26',['query_rounding.md',['../query__rounding_8md.html',1,'']]],
  ['querying_20an_20immutable_20catalog_20chain_27',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['queue_20actually_20finishes_28',['5. Why the replay queue actually finishes',['../md_docs_2rebuild.html#autotoc_md5-why-the-replay-queue-actually-finishes',1,'']]]
];
