var searchData=
[
  ['a_20blob_0',['Build and query a blob',['../index.html#build-and-query-a-blob',1,'']]],
  ['a_20block_1',['Comparison transfer within a block',['../md_docs_2comparison-fc.html#comparison-transfer-within-a-block',1,'']]],
  ['a_20category_20chosen_20per_20key_2',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['a_20chain_3',['Preparing and reopening a chain',['../mapped-blobs-and-exact-query-roots.html#preparing-and-reopening-a-chain',1,'']]],
  ['a_20chain_20while_20retaining_20native_20allocations_4',['Build a chain while retaining native allocations',['../index.html#build-a-chain-while-retaining-native-allocations',1,'']]],
  ['a_20comparison_20belongs_20to_20one_20query_5',['A comparison belongs to one query',['../md_docs_2design.html#a-comparison-belongs-to-one-query',1,'']]],
  ['a_20complete_20logical_20cut_6',['Freeze a complete logical cut',['../md_docs_2rebuild.html#freeze-a-complete-logical-cut',1,'']]],
  ['a_20complete_20publication_20path_7',['A complete publication path',['../md_docs_2sqlite-catalog.html#a-complete-publication-path',1,'']]],
  ['a_20composite_20algebra_8',['7. Hash policies share a composite algebra',['../md_docs_2keys.html#autotoc_md7-hash-policies-share-a-composite-algebra',1,'']]],
  ['a_20family_20of_20categories_9',['1. A family of categories',['../md_docs_2arrows.html#autotoc_md1-a-family-of-categories',1,'']]],
  ['a_20finite_20cut_10',['Adopt at a finite cut',['../md_docs_2rebuild.html#adopt-at-a-finite-cut',1,'']]],
  ['a_20framing_20illustration_20not_20a_20wire_20format_11',['3. A framing illustration, not a wire format',['../md_docs_2keys.html#autotoc_md3-a-framing-illustration-not-a-wire-format',1,'']]],
  ['a_20local_20window_20works_20for_20k_203_12',['2. Why a local window works for K = 3',['../md_docs_2sampling.html#autotoc_md2-why-a-local-window-works-for-k--3',1,'']]],
  ['a_20pair_13',['Writing a pair',['../mapped-blobs-and-exact-query-roots.html#writing-a-pair',1,'']]],
  ['a_20pinned_20pair_14',['Constructing samples from a pinned pair',['../md_docs_2sampling.html#constructing-samples-from-a-pinned-pair',1,'']]],
  ['a_20projected_20stream_15',['a projected stream',['../md_docs_2design.html#entering-a-projected-stream-1',1,'Entering a projected stream'],['../md_docs_2comparison-fc.html#entering-a-projected-stream',1,'Entering a projected stream']]],
  ['a_20real_20external_20pin_16',['Acquire a real external pin',['../md_docs_2catalog.html#acquire-a-real-external-pin',1,'']]],
  ['a_20wire_20format_17',['3. A framing illustration, not a wire format',['../md_docs_2keys.html#autotoc_md3-a-framing-illustration-not-a-wire-format',1,'']]],
  ['a_20world_20and_20apply_20disjoint_20updates_18',['Fork a world and apply disjoint updates',['../index.html#fork-a-world-and-apply-disjoint-updates',1,'']]],
  ['aarch64_20results_19',['Native AArch64 results',['../packed-group-and-bitmap-rank-reductions.html#native-aarch64-results',1,'']]],
  ['abstract_20lean_20model_20',['Abstract Lean model',['../md_docs_2implementation.html#abstract-lean-model',1,'']]],
  ['abstract_20proof_20core_21',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['abstraction_22',['1. Purpose and abstraction',['../md_docs_2design.html#autotoc_md1-purpose-and-abstraction',1,'']]],
  ['accept_23',['accept',['../structeverett_1_1profile__sample__decoder.html#a788e701cfac9fee0e0465e6b01de0e01',1,'everett::profile_sample_decoder']]],
  ['accept_5frecovered_5fpublication_24',['accept_recovered_publication',['../structeverett_1_1merge__publication.html#a1c84cce381c8d0dcee5cc048fdb6a539',1,'everett::merge_publication']]],
  ['acceptance_25',['acceptance',['../md_docs_2design.html#autotoc_md10-bounds-and-acceptance',1,'10. Bounds and acceptance'],['../md_docs_2implementation.html#ownership-and-acceptance',1,'Ownership and acceptance']]],
  ['acceptance_20before_20the_20backend_20is_20called_20durable_26',['9. Acceptance before the backend is called durable',['../md_docs_2catalog.html#autotoc_md9-acceptance-before-the-backend-is-called-durable',1,'']]],
  ['acceptance_20cases_20for_20the_20executor_27',['9. Acceptance cases for the executor',['../md_docs_2rebuild.html#autotoc_md9-acceptance-cases-for-the-executor',1,'']]],
  ['accepted_20encoder_20only_20comparison_28',['Accepted encoder-only comparison',['../md_bench_2sample__frontier.html#accepted-encoder-only-comparison',1,'']]],
  ['accepted_5f_29',['accepted_',['../structeverett_1_1partition__round.html#a1cd28dd19ff11e3669d135b411d6f9ad',1,'everett::partition_round']]],
  ['accepted_5fbatches_30',['accepted_batches',['../structeverett_1_1partition__round.html#ac4a3af5837c070db75e239092ea0b8ad',1,'everett::partition_round']]],
  ['access_20and_20scanning_31',['Opening, access and scanning',['../mapped-blobs-and-exact-query-roots.html#opening-access-and-scanning',1,'']]],
  ['accounting_32',['accounting',['../md_docs_2network-admission.html#autotoc_md2-exact-new-prefix-entry-accounting',1,'2. Exact new-prefix entry accounting'],['../md_bench_2query__compare.html#storage-accounting',1,'Storage accounting']]],
  ['accounting_20and_20backpressure_33',['Accounting and backpressure',['../md_docs_2durability.html#accounting-and-backpressure',1,'']]],
  ['acknowledgment_20checkpoints_20and_20recovery_34',['Acknowledgment, checkpoints and recovery',['../md_docs_2file-lifecycle.html#acknowledgment-checkpoints-and-recovery',1,'']]],
  ['acquire_20a_20real_20external_20pin_35',['Acquire a real external pin',['../md_docs_2catalog.html#acquire-a-real-external-pin',1,'']]],
  ['acquire_5fsave_36',['acquire_save',['../structeverett_1_1sqlite__catalog.html#ac6a5fe14c748a059dffb877db38a3005',1,'everett::sqlite_catalog']]],
  ['acquisition_20and_20garbage_20collection_37',['6. Reader acquisition and garbage collection',['../md_docs_2catalog.html#autotoc_md6-reader-acquisition-and-garbage-collection',1,'']]],
  ['across_20sorts_38',['5. Front coding across sorts',['../md_docs_2keys.html#autotoc_md5-front-coding-across-sorts',1,'']]],
  ['active_39',['active',['../structeverett_1_1mapped__profile.html#a8207c9fcb67168dec57ca7eb488c0160',1,'everett::mapped_profile']]],
  ['actually_20finishes_40',['5. Why the replay queue actually finishes',['../md_docs_2rebuild.html#autotoc_md5-why-the-replay-queue-actually-finishes',1,'']]],
  ['add_41',['add',['../namespaceeverett_1_1profile__detail.html#a2bab47ec0e4286dd450e52df1ba60462',1,'everett::profile_detail::add()'],['../namespaceeverett_1_1elias__fano__detail.html#af7485f7e63cdbe6f6fbc18151756c98b',1,'everett::elias_fano_detail::add()'],['../structeverett_1_1wrapping__fingerprint__algebra.html#a6ae1ab6471d9c9159306f4e5e9b39d48',1,'everett::wrapping_fingerprint_algebra::add()'],['../structeverett_1_1pin__set.html#a616e4d0451d1fb15628b20532ba3ef57',1,'everett::pin_set::add()']]],
  ['add_5fowner_42',['add_owner',['../structeverett_1_1sqlite__catalog.html#ae444cb8bbc39b59fa7c56e4afb615967',1,'everett::sqlite_catalog']]],
  ['add_5fprefix_43',['add_prefix',['../structeverett_1_1rank__groups__view.html#a0c2ee652096f06a904e97b8e7aa1cb06',1,'everett::rank_groups_view::add_prefix()'],['../structeverett_1_1rank15__view.html#afd284d096e28982e915553911554c871',1,'everett::rank15_view::add_prefix()']]],
  ['add_5froot_44',['add_root',['../structeverett_1_1sqlite__catalog.html#a8fac0631535af5ac6df3d69906ccb958',1,'everett::sqlite_catalog']]],
  ['additive_20changes_20of_20state_20potential_45',['4. Fingerprints are exact additive changes of state potential',['../md_docs_2arrows.html#autotoc_md4-fingerprints-are-exact-additive-changes-of-state-potential',1,'']]],
  ['addressing_20counts_20profile_20units_46',['6. Sampling counts entries, addressing counts profile units',['../md_docs_2keys.html#autotoc_md6-sampling-counts-entries-addressing-counts-profile-units',1,'']]],
  ['adjacent_20segments_47',['2. Histories are simplices; merges compose adjacent segments',['../md_docs_2arrows.html#autotoc_md2-histories-are-simplices-merges-compose-adjacent-segments',1,'']]],
  ['admission_48',['SQLite catalog and network admission',['../md_docs_2implementation.html#sqlite-catalog-and-network-admission',1,'']]],
  ['admitting_20sorted_20blobs_20from_20peers_49',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['adopt_50',['4. Freeze, build, replay, adopt',['../md_docs_2rebuild.html#autotoc_md4-freeze-build-replay-adopt',1,'']]],
  ['adopt_20at_20a_20finite_20cut_51',['Adopt at a finite cut',['../md_docs_2rebuild.html#adopt-at-a-finite-cut',1,'']]],
  ['adopt_5fnative_52',['adopt_native',['../structeverett_1_1profile__blob.html#adc96cb5042e86d97183b6dcdbbbfe27d',1,'everett::profile_blob']]],
  ['adopt_5fprepared_53',['adopt_prepared',['../structeverett_1_1query__root.html#aef33b6884dcae121fa0d410d8b5331ba',1,'everett::query_root']]],
  ['adopted_20directly_54',['1. What can be adopted directly',['../md_docs_2network-admission.html#autotoc_md1-what-can-be-adopted-directly',1,'']]],
  ['adopting_20their_20catalog_20roots_55',['5. Publish files before adopting their catalog roots',['../md_docs_2catalog.html#autotoc_md5-publish-files-before-adopting-their-catalog-roots',1,'']]],
  ['advance_56',['advance',['../structeverett_1_1sample__cursor.html#ac8ef03d90886a92000c106bbf55809ef',1,'everett::sample_cursor::advance()'],['../structeverett_1_1mapped__blob_1_1merged__cursor.html#a5dd77146af2e167b4b88b02aec5eb114',1,'everett::mapped_blob::merged_cursor::advance()'],['../structeverett_1_1profile__cursor.html#a99bb3e14eca04bf21021627fd686d943',1,'everett::profile_cursor::advance()'],['../structeverett_1_1native__merge__builder.html#a4d7a850dc36beddb45603bfdbf79a986',1,'everett::native_merge_builder::advance()'],['../structeverett_1_1profile__query__context.html#a4e74527928efde9bf9d102494530c6c1',1,'everett::profile_query_context::advance()']]],
  ['advance_5fcomparison_57',['advance_comparison',['../structeverett_1_1profile__cursor.html#a51bccf0780ce1899f3e6e4618d4b97f9',1,'everett::profile_cursor']]],
  ['advance_5fimpl_58',['advance_impl',['../structeverett_1_1profile__cursor.html#ae23a7308c7677d9c9f0e6774c3e7f5d0',1,'everett::profile_cursor']]],
  ['advance_5fone_59',['advance_one',['../structeverett_1_1index__pipeline.html#aea60cc3910223df56e1307c56ca81b48',1,'everett::index_pipeline']]],
  ['advancement_60',['Specializing cursor advancement',['../md_bench_2sample__advance.html',1,'']]],
  ['affinity_20and_20validation_61',['Features, affinity and validation',['../md_bench_2rank__compare__windows.html#features-affinity-and-validation',1,'']]],
  ['after_62',['after',['../structeverett_1_1world__edit.html#adf3fc300a7ac137ff2d39d08451814eb',1,'everett::world_edit']]],
  ['after_20bit_20arithmetic_20cleanup_63',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['after_20the_20rank_20and_20elias–fano_20refactor_64',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['against_20target_20popcnt_20scalar_65',['Appendix: complete rank against target-POPCNT scalar',['../intel-paths-for-bounded-512-bit-rank-prefixes.html#appendix-complete-rank-against-target-popcnt-scalar',1,'']]],
  ['agents_2emd_66',['AGENTS.md',['../_a_g_e_n_t_s_8md.html',1,'']]],
  ['aggregate_20api_20and_20key_20policies_67',['Aggregate API and key policies',['../md_docs_2implementation.html#aggregate-api-and-key-policies',1,'']]],
  ['agreement_68',['Updates and agreement',['../index.html#updates-and-agreement',1,'']]],
  ['algebra_69',['algebra',['../md_docs_2keys.html#autotoc_md7-hash-policies-share-a-composite-algebra',1,'7. Hash policies share a composite algebra'],['../md_docs_2implementation.html#world-semantics-and-algebra',1,'World semantics and algebra']]],
  ['algebraic_20fingerprint_70',['8. Composite key / algebraic fingerprint',['../md_docs_2design.html#autotoc_md8-composite-key--algebraic-fingerprint',1,'']]],
  ['align_71',['align',['../namespaceeverett_1_1section__detail.html#a04a196b31cb4c76690dc772534d6ac8d',1,'everett::section_detail']]],
  ['all_20borrowed_20key_20literals_72',['All borrowed key literals',['../md_docs_2network-admission.html#all-borrowed-key-literals',1,'']]],
  ['allocations_73',['Build a chain while retaining native allocations',['../index.html#build-a-chain-while-retaining-native-allocations',1,'']]],
  ['along_20one_20chain_74',['3. Per-level augmentation along one chain',['../md_docs_2sampling.html#autotoc_md3-per-level-augmentation-along-one-chain',1,'']]],
  ['an_20abstract_20proof_20core_75',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['an_20exact_20encoded_20pair_76',['Sample an exact encoded pair',['../index.html#sample-an-exact-encoded-pair',1,'']]],
  ['an_20immutable_20catalog_20chain_77',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['anchor_78',['anchor',['../structeverett_1_1profile__decoded__record.html#ac1128744cb294d0c0c0d9e654f9352db',1,'everett::profile_decoded_record::anchor() const &amp;&amp;=delete'],['../structeverett_1_1profile__decoded__record.html#a89f2071fe39242bde9c9409ce1bcd377',1,'everett::profile_decoded_record::anchor() const &amp;']]],
  ['and_20abstraction_79',['1. Purpose and abstraction',['../md_docs_2design.html#autotoc_md1-purpose-and-abstraction',1,'']]],
  ['and_20acceptance_80',['and acceptance',['../md_docs_2design.html#autotoc_md10-bounds-and-acceptance',1,'10. Bounds and acceptance'],['../md_docs_2implementation.html#ownership-and-acceptance',1,'Ownership and acceptance']]],
  ['and_20agreement_81',['Updates and agreement',['../index.html#updates-and-agreement',1,'']]],
  ['and_20algebra_82',['World semantics and algebra',['../md_docs_2implementation.html#world-semantics-and-algebra',1,'']]],
  ['and_20apply_20disjoint_20updates_83',['Fork a world and apply disjoint updates',['../index.html#fork-a-world-and-apply-disjoint-updates',1,'']]],
  ['and_20artifacts_84',['Reproduction and artifacts',['../cold-exception-paths-in-complete-queries.html#reproduction-and-artifacts',1,'']]],
  ['and_20background_20work_85',['and background work',['../md_docs_2catalog.html#operations-and-background-work',1,'Operations and background work'],['../md_docs_2catalog.html',1,'SQLite catalog for worlds, pins and background work']]],
  ['and_20backpressure_86',['Accounting and backpressure',['../md_docs_2durability.html#accounting-and-backpressure',1,'']]],
  ['and_20bit_20profiles_87',['and bit profiles',['../md_docs_2keys.html#autotoc_md2-byte-and-bit-profiles',1,'2. Byte and bit profiles'],['../md_docs_2implementation.html#typed-byte-and-bit-profiles',1,'Typed byte and bit profiles']]],
  ['and_20bitmap_20rank_20reductions_88',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['and_20boundaries_89',['Correctness and boundaries',['../md_bench_2key__bits.html#correctness-and-boundaries',1,'']]],
  ['and_20cache_20comparisons_90',['Storage and cache comparisons',['../md_bench_2rank__compare.html#storage-and-cache-comparisons',1,'']]],
  ['and_20checks_91',['and checks',['../md_docs_2keys.html#autotoc_md9-implementation-boundary-and-checks',1,'9. Implementation boundary and checks'],['../md_bench_2native__prefix.html#change-and-checks',1,'Change and checks'],['../blob-and-pipeline-performance.html#inputs-and-checks',1,'Inputs and checks'],['../md_bench_2rank__compare.html#method-and-checks',1,'Method and checks'],['../md_bench_2query__chain.html#reproduction-and-checks',1,'Reproduction and checks']]],
  ['and_20commands_92',['Pinned inputs and commands',['../md_bench_2rank__compare__windows.html#pinned-inputs-and-commands',1,'']]],
  ['and_20comparison_20context_93',['4. Front coding and comparison context',['../md_docs_2design.html#autotoc_md4-front-coding-and-comparison-context',1,'']]],
  ['and_20comparison_20transfers_94',['String prefixes and comparison transfers',['../everett-an-abstract-proof-core.html#string-prefixes-and-comparison-transfers',1,'']]],
  ['and_20completion_95',['Value widths and completion',['../md_docs_2native-merges.html#value-widths-and-completion',1,'']]],
  ['and_20constraints_96',['Value encodings and constraints',['../md_docs_2catalog.html#value-encodings-and-constraints',1,'']]],
  ['and_20construction_97',['Elias–Fano Selection and Construction',['../eliasfano-selection-and-construction.html',1,'']]],
  ['and_20content_20identity_98',['Path spelling and content identity',['../md_docs_2file-lifecycle.html#path-spelling-and-content-identity',1,'']]],
  ['and_20correctness_99',['and correctness',['../complete-queries-after-the-rank-and-eliasfano-refactor.html#encoded-arrays-and-correctness',1,'Encoded arrays and correctness'],['../md_bench_2sample__advance.html#isolated-change-and-correctness',1,'Isolated change and correctness']]],
  ['and_20declaration_20ownership_100',['Doxygen metadata and declaration ownership',['../md_docs_2doxygen.html',1,'']]],
  ['and_20durable_20continuation_101',['7. Coverage, contributions and durable continuation',['../md_docs_2rebuild.html#autotoc_md7-coverage-contributions-and-durable-continuation',1,'']]],
  ['and_20elias–fano_20refactor_102',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['and_20encoder_20reuse_103',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['and_20equality_104',['False borrows and equality',['../md_docs_2design.html#false-borrows-and-equality',1,'']]],
  ['and_20evaluation_20cost_20separate_105',['5. Navigation cost and evaluation cost separate',['../md_docs_2arrows.html#autotoc_md5-navigation-cost-and-evaluation-cost-separate',1,'']]],
  ['and_20exact_20layouts_106',['Contents and exact layouts',['../md_docs_2catalog.html#contents-and-exact-layouts',1,'']]],
  ['and_20exact_20query_20roots_107',['Mapped blobs and exact query roots',['../mapped-blobs-and-exact-query-roots.html',1,'']]],
  ['and_20exception_20guarantee_108',['Change and exception guarantee',['../md_bench_2borrowed__prefix.html#change-and-exception-guarantee',1,'']]],
  ['and_20fixed_20width_20values_109',['Physical offsets and fixed-width values',['../md_docs_2design.html#physical-offsets-and-fixed-width-values',1,'']]],
  ['and_20framed_20output_110',['Native merge frontiers and framed output',['../native-merge-frontiers-and-framed-output.html',1,'']]],
  ['and_20framing_111',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['and_20garbage_20collection_112',['6. Reader acquisition and garbage collection',['../md_docs_2catalog.html#autotoc_md6-reader-acquisition-and-garbage-collection',1,'']]],
  ['and_20global_20rebuilding_113',['Strong deletes and global rebuilding',['../md_docs_2implementation.html#strong-deletes-and-global-rebuilding',1,'']]],
  ['and_20implementation_20boundary_114',['Pins integration and implementation boundary',['../md_docs_2durability.html#pins-integration-and-implementation-boundary',1,'']]],
  ['and_20implementation_20scope_115',['Validation and implementation scope',['../cold-exception-paths-in-complete-queries.html#validation-and-implementation-scope',1,'']]],
  ['and_20key_20policies_116',['Aggregate API and key policies',['../md_docs_2implementation.html#aggregate-api-and-key-policies',1,'']]],
  ['and_20limits_117',['and limits',['../immutable-object-sealing.html#failure-and-limits',1,'Failure and limits'],['../eliasfano-selection-and-construction.html#rejected-prototypes-and-limits',1,'Rejected prototypes and limits'],['../md_bench_2sample__frontier.html#reproduction-and-limits',1,'Reproduction and limits'],['../packed-group-and-bitmap-rank-reductions.html#validation-and-limits',1,'Validation and limits']]],
  ['and_20live_20count_20checks_118',['Hash and live-count checks',['../md_docs_2rebuild.html#hash-and-live-count-checks',1,'']]],
  ['and_20live_20universe_20rebuilding_119',['7. Strong deletes and live-universe rebuilding',['../md_docs_2design.html#autotoc_md7-strong-deletes-and-live-universe-rebuilding',1,'']]],
  ['and_20mapped_20query_20chains_120',['Portable sections and mapped query chains',['../md_docs_2implementation.html#portable-sections-and-mapped-query-chains',1,'']]],
  ['and_20math_121',['Markdown pages and math',['../md_docs_2doxygen.html#markdown-pages-and-math',1,'']]],
  ['and_20measurements_122',['Tests and measurements',['../md_docs_2implementation.html#tests-and-measurements',1,'']]],
  ['and_20merge_20resumption_123',['and merge resumption',['../md_docs_2implementation.html#durability-and-merge-resumption',1,'Durability and merge resumption'],['../md_docs_2durability.html',1,'Durable publication and merge resumption']]],
  ['and_20merge_20work_124',['5. Redundant levels and merge work',['../md_docs_2design.html#autotoc_md5-redundant-levels-and-merge-work',1,'']]],
  ['and_20merging_125',['Incremental native writing and merging',['../md_docs_2native-merges.html',1,'']]],
  ['and_20method_126',['Host and method',['../native-avx2-packed-rank-comparison.html#host-and-method',1,'']]],
  ['and_20multiplicity_127',['Logical key identity and multiplicity',['../md_docs_2arrows.html#logical-key-identity-and-multiplicity',1,'']]],
  ['and_20mutable_20selections_128',['Retention roots and mutable selections',['../md_docs_2catalog.html#retention-roots-and-mutable-selections',1,'']]],
  ['and_20names_129',['Objects and names',['../md_docs_2file-lifecycle.html#objects-and-names',1,'']]],
  ['and_20network_20admission_130',['SQLite catalog and network admission',['../md_docs_2implementation.html#sqlite-catalog-and-network-admission',1,'']]],
  ['and_20next_20contract_131',['7. Implementation boundary and next contract',['../md_docs_2arrows.html#autotoc_md7-implementation-boundary-and-next-contract',1,'']]],
  ['and_20offsets_132',['String compression and offsets',['../index.html#string-compression-and-offsets',1,'']]],
  ['and_20operation_20identities_133',['Transactions and operation identities',['../md_docs_2sqlite-catalog.html#transactions-and-operation-identities',1,'']]],
  ['and_20oracle_134',['Method and oracle',['../md_bench_2sample__frontier.html#method-and-oracle',1,'']]],
  ['and_20order_135',['1. One canonical identity and order',['../md_docs_2keys.html#autotoc_md1-one-canonical-identity-and-order',1,'']]],
  ['and_20ordered_20merges_136',['Incremental native output and ordered merges',['../md_docs_2implementation.html#incremental-native-output-and-ordered-merges',1,'']]],
  ['and_20ownership_137',['and ownership',['../index.html#blobs-worlds-and-ownership',1,'Blobs, worlds, and ownership'],['../md_docs_2native-merges.html#work-and-ownership',1,'Work and ownership']]],
  ['and_20ownership_20bounds_138',['Work and ownership bounds',['../md_docs_2query.html#work-and-ownership-bounds',1,'']]],
  ['and_20packed_20rank_20comparison_139',['Full-vector and packed-rank comparison',['../md_bench_2rank__compare.html',1,'']]],
  ['and_20padding_140',['4. Bit lengths, units, and padding',['../md_docs_2keys.html#autotoc_md4-bit-lengths-units-and-padding',1,'']]],
  ['and_20peak_20retained_20space_141',['4. String bytes and peak retained space',['../md_docs_2network-admission.html#autotoc_md4-string-bytes-and-peak-retained-space',1,'']]],
  ['and_20pipeline_20performance_142',['Blob and pipeline performance',['../blob-and-pipeline-performance.html',1,'']]],
  ['and_20preserve_20the_20next_20generation_20s_20slack_143',['3. Trigger early and preserve the next generation&apos;s slack',['../md_docs_2rebuild.html#autotoc_md3-trigger-early-and-preserve-the-next-generations-slack',1,'']]],
  ['and_20provenance_144',['Reproduction and provenance',['../native-merge-frontiers-and-framed-output.html#reproduction-and-provenance',1,'']]],
  ['and_20publication_145',['Files, mappings and publication',['../md_docs_2file-lifecycle.html',1,'']]],
  ['and_20published_20state_146',['5. Ingestion state and published state',['../md_docs_2network-admission.html#autotoc_md5-ingestion-state-and-published-state',1,'']]],
  ['and_20query_20a_20blob_147',['Build and query a blob',['../index.html#build-and-query-a-blob',1,'']]],
  ['and_20rebuilding_20progress_148',['7. Checkpoints and rebuilding progress',['../md_docs_2catalog.html#autotoc_md7-checkpoints-and-rebuilding-progress',1,'']]],
  ['and_20recovery_149',['Acknowledgment, checkpoints and recovery',['../md_docs_2file-lifecycle.html#acknowledgment-checkpoints-and-recovery',1,'']]],
  ['and_20reductions_150',['Sources and reductions',['../native-avx2-packed-rank-comparison.html#sources-and-reductions',1,'']]],
  ['and_20remaining_20proof_20work_151',['7. Executable evidence and remaining proof work',['../md_docs_2sampling.html#autotoc_md7-executable-evidence-and-remaining-proof-work',1,'']]],
  ['and_20reopening_20a_20chain_152',['Preparing and reopening a chain',['../mapped-blobs-and-exact-query-roots.html#preparing-and-reopening-a-chain',1,'']]],
  ['and_20reproduction_153',['and reproduction',['../md_bench_2query__rounding.html#correctness-storage-and-reproduction',1,'Correctness, storage and reproduction'],['../complete-queries-after-the-rank-and-eliasfano-refactor.html#method-and-reproduction',1,'Method and reproduction'],['../eliasfano-selection-and-construction.html#validation-and-reproduction',1,'Validation and reproduction']]],
  ['and_20reservations_154',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['and_20results_155',['Shared input and results',['../md_bench_2rank__compare__windows.html#shared-input-and-results',1,'']]],
  ['and_20resume_156',['Work that can stop and resume',['../index.html#work-that-can-stop-and-resume',1,'']]],
  ['and_20resumption_157',['Durability and resumption',['../md_docs_2design.html#durability-and-resumption',1,'']]],
  ['and_20run_158',['Build and run',['../everett-an-abstract-proof-core.html#build-and-run',1,'']]],
  ['and_20scan_20work_159',['4. Space and scan work',['../md_docs_2sampling.html#autotoc_md4-space-and-scan-work',1,'']]],
  ['and_20scanning_160',['Opening, access and scanning',['../mapped-blobs-and-exact-query-roots.html#opening-access-and-scanning',1,'']]],
  ['and_20scheduling_20obligations_161',['3. Query bounds and scheduling obligations',['../md_docs_2network-admission.html#autotoc_md3-query-bounds-and-scheduling-obligations',1,'']]],
  ['and_20scope_162',['Revisions and scope',['../complete-queries-after-the-rank-and-eliasfano-refactor.html#revisions-and-scope',1,'']]],
  ['and_20shared_20work_163',['6. Snapshots, saves, and shared work',['../md_docs_2design.html#autotoc_md6-snapshots-saves-and-shared-work',1,'']]],
  ['and_20sparse_20offsets_164',['Rank and sparse offsets',['../md_docs_2implementation.html#rank-and-sparse-offsets',1,'']]],
  ['and_20stringlike_20keys_165',['Sorts and stringlike keys',['../md_docs_2keys.html',1,'']]],
  ['and_20strong_20deletion_166',['6. Blobs, pins, checkpoints and strong deletion',['../md_docs_2arrows.html#autotoc_md6-blobs-pins-checkpoints-and-strong-deletion',1,'']]],
  ['and_20the_20choice_20of_20k_167',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['and_20the_20cult_20bitmap_20rank_168',['NEON reductions and the Cult bitmap rank',['../md_bench_2neon__cult__rank.html',1,'']]],
  ['and_20their_20roles_169',['11. References and their roles',['../md_docs_2design.html#autotoc_md11-references-and-their-roles',1,'']]],
  ['and_20their_20separate_20costs_170',['Construction, queries, and their separate costs',['../md_docs_2design.html#construction-queries-and-their-separate-costs',1,'']]],
  ['and_20transaction_20policy_171',['4. Connection and transaction policy',['../md_docs_2catalog.html#autotoc_md4-connection-and-transaction-policy',1,'']]],
  ['and_20trigger_172',['Generation state and trigger',['../md_docs_2design.html#generation-state-and-trigger',1,'']]],
  ['and_20trust_173',['Construction and trust',['../md_docs_2query.html#construction-and-trust',1,'']]],
  ['and_20type_20family_174',['Object envelopes, mappings and type family',['../md_docs_2implementation.html#object-envelopes-mappings-and-type-family',1,'']]],
  ['and_20use_175',['Build and use',['../md_docs_2sqlite-catalog.html#build-and-use',1,'']]],
  ['and_20validation_176',['and validation',['../md_bench_2rank__compare__windows.html#features-affinity-and-validation',1,'Features, affinity and validation'],['../md_bench_2neon__cult__rank.html#method-and-validation',1,'Method and validation'],['../stored-spacers-in-complete-bitmap-rank.html#scope-and-validation',1,'Scope and validation']]],
  ['and_20verification_177',['and verification',['../md_docs_2implementation.html#build-and-verification',1,'Build and verification'],['../intel-paths-for-bounded-512-bit-rank-prefixes.html#measurement-and-verification',1,'Measurement and verification'],['../md_bench_2query__compare.html#reproduction-and-verification',1,'Reproduction and verification'],['../md__a_g_e_n_t_s.html#work-and-verification',1,'Work and verification']]],
  ['and_20verification_20boundary_178',['Axiom audit and verification boundary',['../everett-an-abstract-proof-core.html#axiom-audit-and-verification-boundary',1,'']]],
  ['api_20and_20key_20policies_179',['Aggregate API and key policies',['../md_docs_2implementation.html#aggregate-api-and-key-policies',1,'']]],
  ['append_180',['append',['../structeverett_1_1profile__borrowed__writer.html#a19f9f74fe5c201322df2f1984f165d1e',1,'everett::profile_borrowed_writer::append()'],['../structeverett_1_1native__merge__builder.html#a30e6b9a846826328de472cb3390deec8',1,'everett::native_merge_builder::append()'],['../structeverett_1_1reference__world.html#a009c0d70ad0efe5727c2789128b64069',1,'everett::reference_world::append()'],['../namespaceeverett_1_1profile__detail.html#aeaaf0159830d6d5bbd9a0d22e1ad7bb3',1,'everett::profile_detail::append()'],['../structeverett_1_1profile__native__writer.html#a765f562173053ea62c8187c138d0826b',1,'everett::profile_native_writer::append()'],['../structeverett_1_1profile__detail_1_1native__output.html#a1117dcdb9327b135182b45ed2dc24753',1,'everett::profile_detail::native_output::append()'],['../structeverett_1_1profile__native__writer.html#a3a348fe4b777ebcc9bcb5062930a6863',1,'everett::profile_native_writer::append()']]],
  ['append_5fbit_181',['append_bit',['../namespaceeverett_1_1profile__detail.html#a1da1b0de6f437ea3e3ed477e85b553e7',1,'everett::profile_detail']]],
  ['append_5fbyte_182',['append_byte',['../namespaceeverett_1_1profile__detail.html#a7f1e2f179a9d5b9f88b1ba1288b698b4',1,'everett::profile_detail']]],
  ['appendix_3a_20complete_20rank_20against_20target_20popcnt_20scalar_183',['Appendix: complete rank against target-POPCNT scalar',['../intel-paths-for-bounded-512-bit-rank-prefixes.html#appendix-complete-rank-against-target-popcnt-scalar',1,'']]],
  ['appendix_3a_20prefix_20only_20measurements_184',['Appendix: prefix-only measurements',['../intel-paths-for-bounded-512-bit-rank-prefixes.html#appendix-prefix-only-measurements',1,'']]],
  ['apple_5ffull_5ffsync_185',['apple_full_fsync',['../namespaceeverett.html#abd194330a17cff6ed35dcb16a197198ea5f9cafb30deb28e844ef3bf235cb3e4c',1,'everett']]],
  ['applied_186',['applied',['../namespaceeverett.html#abdd0012244f6054f1fd40fe06a2f3a0baad8437d4bf608f79c1f0de5b5f54d31b',1,'everett']]],
  ['apply_187',['apply',['../structeverett_1_1partition__round.html#a343c5b9ae5f295cc0d9be6b8af07873c',1,'everett::partition_round']]],
  ['apply_20disjoint_20updates_188',['Fork a world and apply disjoint updates',['../index.html#fork-a-world-and-apply-disjoint-updates',1,'']]],
  ['are_20exact_20additive_20changes_20of_20state_20potential_189',['4. Fingerprints are exact additive changes of state potential',['../md_docs_2arrows.html#autotoc_md4-fingerprints-are-exact-additive-changes-of-state-potential',1,'']]],
  ['are_20not_20bytes_190',['8. Records are not bytes',['../md_docs_2rebuild.html#autotoc_md8-records-are-not-bytes',1,'']]],
  ['are_20not_20retention_20counts_191',['3. Contributions are not retention counts',['../md_docs_2catalog.html#autotoc_md3-contributions-are-not-retention-counts',1,'']]],
  ['are_20simplices_20merges_20compose_20adjacent_20segments_192',['2. Histories are simplices; merges compose adjacent segments',['../md_docs_2arrows.html#autotoc_md2-histories-are-simplices-merges-compose-adjacent-segments',1,'']]],
  ['arithmetic_20cleanup_193',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['array_20path_194',['Final owning-array path',['../md_bench_2shared__query.html#final-owning-array-path',1,'']]],
  ['arrays_20and_20correctness_195',['Encoded arrays and correctness',['../complete-queries-after-the-rank-and-eliasfano-refactor.html#encoded-arrays-and-correctness',1,'']]],
  ['arrows_2emd_196',['arrows.md',['../arrows_8md.html',1,'']]],
  ['artifacts_197',['Reproduction and artifacts',['../cold-exception-paths-in-complete-queries.html#reproduction-and-artifacts',1,'']]],
  ['assembly_20probe_198',['Separate subview assembly probe',['../md_bench_2sample__advance.html#separate-subview-assembly-probe',1,'']]],
  ['assignments_199',['Next implementation assignments',['../md_docs_2implementation.html#next-implementation-assignments',1,'']]],
  ['assumptions_20mean_200',['What the assumptions mean',['../everett-an-abstract-proof-core.html#what-the-assumptions-mean',1,'']]],
  ['at_201',['at',['../structeverett_1_1bit__view.html#a13a55df6f40ec03b4fc0347c19005168',1,'everett::bit_view']]],
  ['at_20a_20finite_20cut_202',['Adopt at a finite cut',['../md_docs_2rebuild.html#adopt-at-a-finite-cut',1,'']]],
  ['attempt_203',['attempt',['../structeverett_1_1object__seal__receipt.html#a0dbafc0aca14e103b3aa25e159470b7d',1,'everett::object_seal_receipt::attempt'],['../structeverett_1_1object__write__error.html#a5273bc794420be1118367e256fb7ee74',1,'everett::object_write_error::attempt'],['../structeverett_1_1object__writer_1_1operation.html#a3da141bdc01752caca68f17b953a3d5d',1,'everett::object_writer::operation::attempt']]],
  ['audit_20and_20verification_20boundary_204',['Axiom audit and verification boundary',['../everett-an-abstract-proof-core.html#axiom-audit-and-verification-boundary',1,'']]],
  ['augmentation_20along_20one_20chain_205',['3. Per-level augmentation along one chain',['../md_docs_2sampling.html#autotoc_md3-per-level-augmentation-along-one-chain',1,'']]],
  ['available_206',['Replay while the foreground remains available',['../md_docs_2rebuild.html#replay-while-the-foreground-remains-available',1,'']]],
  ['avx2_20packed_20rank_20comparison_207',['Native AVX2 packed-rank comparison',['../native-avx2-packed-rank-comparison.html',1,'']]],
  ['axiom_20audit_20and_20verification_20boundary_208',['Axiom audit and verification boundary',['../everett-an-abstract-proof-core.html#axiom-audit-and-verification-boundary',1,'']]]
];
