var searchData=
[
  ['a_20blob_0',['Build and query a blob',['../index.html#build-and-query-a-blob',1,'']]],
  ['a_20byte_20bound_1',['4. Entry accounting is not a byte bound',['../md_docs_2network-admission.html#autotoc_md4-entry-accounting-is-not-a-byte-bound',1,'']]],
  ['a_20category_20chosen_20per_20key_2',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['a_20chain_20while_20retaining_20native_20allocations_3',['Build a chain while retaining native allocations',['../index.html#build-a-chain-while-retaining-native-allocations',1,'']]],
  ['a_20complete_20logical_20cut_4',['Freeze a complete logical cut',['../md_docs_2rebuild.html#freeze-a-complete-logical-cut',1,'']]],
  ['a_20composite_20algebra_5',['7. Hash policies share a composite algebra',['../md_docs_2keys.html#autotoc_md7-hash-policies-share-a-composite-algebra',1,'']]],
  ['a_20concrete_20index_20only_20construction_6',['A concrete index-only construction',['../md_docs_2design.html#a-concrete-index-only-construction',1,'']]],
  ['a_20family_20of_20categories_7',['1. A family of categories',['../md_docs_2arrows.html#autotoc_md1-a-family-of-categories',1,'']]],
  ['a_20finite_20cut_8',['Adopt at a finite cut',['../md_docs_2rebuild.html#adopt-at-a-finite-cut',1,'']]],
  ['a_20framing_20illustration_20not_20a_20wire_20format_9',['3. A framing illustration, not a wire format',['../md_docs_2keys.html#autotoc_md3-a-framing-illustration-not-a-wire-format',1,'']]],
  ['a_20local_20window_20works_20for_20k_203_10',['2. Why a local window works for K = 3',['../md_docs_2sampling.html#autotoc_md2-why-a-local-window-works-for-k--3',1,'']]],
  ['a_20pinned_20pair_11',['Constructing samples from a pinned pair',['../md_docs_2sampling.html#constructing-samples-from-a-pinned-pair',1,'']]],
  ['a_20real_20external_20pin_12',['Acquire a real external pin',['../md_docs_2catalog.html#acquire-a-real-external-pin',1,'']]],
  ['a_20wire_20format_13',['3. A framing illustration, not a wire format',['../md_docs_2keys.html#autotoc_md3-a-framing-illustration-not-a-wire-format',1,'']]],
  ['a_20world_20and_20apply_20disjoint_20updates_14',['Fork a world and apply disjoint updates',['../index.html#fork-a-world-and-apply-disjoint-updates',1,'']]],
  ['aarch64_20results_15',['Native AArch64 results',['../packed-group-and-bitmap-rank-reductions.html#native-aarch64-results',1,'']]],
  ['abstract_20lean_20model_16',['Abstract Lean model',['../md_docs_2implementation.html#abstract-lean-model',1,'']]],
  ['abstract_20proof_20core_17',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['abstraction_18',['1. Purpose and abstraction',['../md_docs_2design.html#autotoc_md1-purpose-and-abstraction',1,'']]],
  ['accept_19',['accept',['../structeverett_1_1profile__sample__decoder.html#a788e701cfac9fee0e0465e6b01de0e01',1,'everett::profile_sample_decoder']]],
  ['accept_5frecovered_5fpublication_20',['accept_recovered_publication',['../structeverett_1_1merge__publication.html#a1c84cce381c8d0dcee5cc048fdb6a539',1,'everett::merge_publication']]],
  ['acceptance_21',['acceptance',['../md_docs_2design.html#autotoc_md10-bounds-and-acceptance',1,'10. Bounds and acceptance'],['../md_docs_2implementation.html#ownership-and-acceptance',1,'Ownership and acceptance']]],
  ['acceptance_20before_20the_20backend_20is_20called_20durable_22',['9. Acceptance before the backend is called durable',['../md_docs_2catalog.html#autotoc_md9-acceptance-before-the-backend-is-called-durable',1,'']]],
  ['acceptance_20cases_20for_20the_20executor_23',['9. Acceptance cases for the executor',['../md_docs_2rebuild.html#autotoc_md9-acceptance-cases-for-the-executor',1,'']]],
  ['accepted_5f_24',['accepted_',['../structeverett_1_1partition__round.html#a1cd28dd19ff11e3669d135b411d6f9ad',1,'everett::partition_round']]],
  ['accepted_5fbatches_25',['accepted_batches',['../structeverett_1_1partition__round.html#ac4a3af5837c070db75e239092ea0b8ad',1,'everett::partition_round']]],
  ['accounting_26',['2. Exact new-prefix entry accounting',['../md_docs_2network-admission.html#autotoc_md2-exact-new-prefix-entry-accounting',1,'']]],
  ['accounting_20and_20backpressure_27',['Accounting and backpressure',['../md_docs_2durability.html#accounting-and-backpressure',1,'']]],
  ['accounting_20is_20not_20a_20byte_20bound_28',['4. Entry accounting is not a byte bound',['../md_docs_2network-admission.html#autotoc_md4-entry-accounting-is-not-a-byte-bound',1,'']]],
  ['acknowledgment_20checkpoints_20and_20recovery_29',['Acknowledgment, checkpoints and recovery',['../md_docs_2file-lifecycle.html#acknowledgment-checkpoints-and-recovery',1,'']]],
  ['acquire_20a_20real_20external_20pin_30',['Acquire a real external pin',['../md_docs_2catalog.html#acquire-a-real-external-pin',1,'']]],
  ['acquisition_20and_20garbage_20collection_31',['6. Reader acquisition and garbage collection',['../md_docs_2catalog.html#autotoc_md6-reader-acquisition-and-garbage-collection',1,'']]],
  ['across_20sorts_32',['5. Front coding across sorts',['../md_docs_2keys.html#autotoc_md5-front-coding-across-sorts',1,'']]],
  ['actually_20finishes_33',['5. Why the replay queue actually finishes',['../md_docs_2rebuild.html#autotoc_md5-why-the-replay-queue-actually-finishes',1,'']]],
  ['add_34',['add',['../namespaceeverett_1_1select15__detail.html#a6450e79059a0234017ed1b1ab94f30a0',1,'everett::select15_detail::add()'],['../namespaceeverett_1_1profile__detail.html#a2bab47ec0e4286dd450e52df1ba60462',1,'everett::profile_detail::add()'],['../namespaceeverett_1_1select__groups__detail.html#a5d967bb12ddbe68c01f55e934d9fd61a',1,'everett::select_groups_detail::add()'],['../structeverett_1_1pin__set.html#a616e4d0451d1fb15628b20532ba3ef57',1,'everett::pin_set::add()'],['../structeverett_1_1wrapping__fingerprint__algebra.html#a6ae1ab6471d9c9159306f4e5e9b39d48',1,'everett::wrapping_fingerprint_algebra::add()']]],
  ['additive_20changes_20of_20state_20potential_35',['4. Fingerprints are exact additive changes of state potential',['../md_docs_2arrows.html#autotoc_md4-fingerprints-are-exact-additive-changes-of-state-potential',1,'']]],
  ['addressing_20counts_20profile_20units_36',['6. Sampling counts entries, addressing counts profile units',['../md_docs_2keys.html#autotoc_md6-sampling-counts-entries-addressing-counts-profile-units',1,'']]],
  ['adjacent_20segments_37',['2. Histories are simplices; merges compose adjacent segments',['../md_docs_2arrows.html#autotoc_md2-histories-are-simplices-merges-compose-adjacent-segments',1,'']]],
  ['admission_38',['SQLite catalog and network admission',['../md_docs_2implementation.html#sqlite-catalog-and-network-admission',1,'']]],
  ['admitting_20sorted_20blobs_20from_20peers_39',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['adopt_40',['4. Freeze, build, replay, adopt',['../md_docs_2rebuild.html#autotoc_md4-freeze-build-replay-adopt',1,'']]],
  ['adopt_20at_20a_20finite_20cut_41',['Adopt at a finite cut',['../md_docs_2rebuild.html#adopt-at-a-finite-cut',1,'']]],
  ['adopted_20directly_42',['1. What can be adopted directly',['../md_docs_2network-admission.html#autotoc_md1-what-can-be-adopted-directly',1,'']]],
  ['adopting_20their_20catalog_20roots_43',['5. Publish files before adopting their catalog roots',['../md_docs_2catalog.html#autotoc_md5-publish-files-before-adopting-their-catalog-roots',1,'']]],
  ['advance_44',['advance',['../structeverett_1_1profile__cursor.html#a99bb3e14eca04bf21021627fd686d943',1,'everett::profile_cursor::advance()'],['../structeverett_1_1sample__cursor.html#ac8ef03d90886a92000c106bbf55809ef',1,'everett::sample_cursor::advance()']]],
  ['advance_5fone_45',['advance_one',['../structeverett_1_1index__pipeline.html#aea60cc3910223df56e1307c56ca81b48',1,'everett::index_pipeline']]],
  ['affinity_20and_20validation_46',['Features, affinity and validation',['../md_bench_2rank__compare__windows.html#features-affinity-and-validation',1,'']]],
  ['after_47',['after',['../structeverett_1_1world__edit.html#adf3fc300a7ac137ff2d39d08451814eb',1,'everett::world_edit']]],
  ['agents_2emd_48',['AGENTS.md',['../_a_g_e_n_t_s_8md.html',1,'']]],
  ['aggregate_20api_20and_20key_20policies_49',['Aggregate API and key policies',['../md_docs_2implementation.html#aggregate-api-and-key-policies',1,'']]],
  ['agreement_50',['Updates and agreement',['../index.html#updates-and-agreement',1,'']]],
  ['algebra_51',['algebra',['../md_docs_2keys.html#autotoc_md7-hash-policies-share-a-composite-algebra',1,'7. Hash policies share a composite algebra'],['../md_docs_2implementation.html#world-semantics-and-algebra',1,'World semantics and algebra']]],
  ['algebraic_20fingerprint_52',['8. Composite key / algebraic fingerprint',['../md_docs_2design.html#autotoc_md8-composite-key--algebraic-fingerprint',1,'']]],
  ['alignment_53',['Conservative common-prefix alignment',['../md_docs_2design.html#conservative-common-prefix-alignment',1,'']]],
  ['allocations_54',['Build a chain while retaining native allocations',['../index.html#build-a-chain-while-retaining-native-allocations',1,'']]],
  ['along_20one_20chain_55',['3. Per-level augmentation along one chain',['../md_docs_2sampling.html#autotoc_md3-per-level-augmentation-along-one-chain',1,'']]],
  ['an_20abstract_20proof_20core_56',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['an_20exact_20encoded_20pair_57',['Sample an exact encoded pair',['../index.html#sample-an-exact-encoded-pair',1,'']]],
  ['anchor_58',['anchor',['../structeverett_1_1profile__decoded__record.html#ac1128744cb294d0c0c0d9e654f9352db',1,'everett::profile_decoded_record::anchor() const &amp;&amp;=delete'],['../structeverett_1_1profile__decoded__record.html#a89f2071fe39242bde9c9409ce1bcd377',1,'everett::profile_decoded_record::anchor() const &amp;'],['../structeverett_1_1profile__blob__borrowed__predecessor.html#a5dee8c5a60d62176ab2614fcc84ed0ba',1,'everett::profile_blob_borrowed_predecessor::anchor() const &amp;'],['../structeverett_1_1profile__blob__borrowed__predecessor.html#a22625a1373a5c97e627f356275cbc761',1,'everett::profile_blob_borrowed_predecessor::anchor() const &amp;&amp;=delete'],['../structeverett_1_1front__decoded__record.html#ab44bbaa7cdd0a5f9f015c86793223f94',1,'everett::front_decoded_record::anchor()']]],
  ['anchored_20decoding_20and_20its_20limits_59',['Anchored decoding and its limits',['../md_docs_2design.html#anchored-decoding-and-its-limits',1,'']]],
  ['and_20abstraction_60',['1. Purpose and abstraction',['../md_docs_2design.html#autotoc_md1-purpose-and-abstraction',1,'']]],
  ['and_20acceptance_61',['and acceptance',['../md_docs_2design.html#autotoc_md10-bounds-and-acceptance',1,'10. Bounds and acceptance'],['../md_docs_2implementation.html#ownership-and-acceptance',1,'Ownership and acceptance']]],
  ['and_20agreement_62',['Updates and agreement',['../index.html#updates-and-agreement',1,'']]],
  ['and_20algebra_63',['World semantics and algebra',['../md_docs_2implementation.html#world-semantics-and-algebra',1,'']]],
  ['and_20apply_20disjoint_20updates_64',['Fork a world and apply disjoint updates',['../index.html#fork-a-world-and-apply-disjoint-updates',1,'']]],
  ['and_20background_20work_65',['and background work',['../md_docs_2catalog.html#operations-and-background-work',1,'Operations and background work'],['../md_docs_2catalog.html',1,'SQLite catalog for worlds, pins and background work']]],
  ['and_20backpressure_66',['Accounting and backpressure',['../md_docs_2durability.html#accounting-and-backpressure',1,'']]],
  ['and_20bit_20profiles_67',['and bit profiles',['../md_docs_2keys.html#autotoc_md2-byte-and-bit-profiles',1,'2. Byte and bit profiles'],['../md_docs_2implementation.html#typed-byte-and-bit-profiles',1,'Typed byte and bit profiles']]],
  ['and_20bitmap_20rank_20reductions_68',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['and_20boundaries_69',['Correctness and boundaries',['../md_bench_2key__bits.html#correctness-and-boundaries',1,'']]],
  ['and_20cache_20comparisons_70',['Storage and cache comparisons',['../md_bench_2rank__compare.html#storage-and-cache-comparisons',1,'']]],
  ['and_20checks_71',['and checks',['../md_docs_2keys.html#autotoc_md9-implementation-boundary-and-checks',1,'9. Implementation boundary and checks'],['../blob-and-pipeline-performance.html#inputs-and-checks',1,'Inputs and checks'],['../md_bench_2rank__compare.html#method-and-checks',1,'Method and checks']]],
  ['and_20commands_72',['Pinned inputs and commands',['../md_bench_2rank__compare__windows.html#pinned-inputs-and-commands',1,'']]],
  ['and_20constraints_73',['Value encodings and constraints',['../md_docs_2catalog.html#value-encodings-and-constraints',1,'']]],
  ['and_20construction_74',['Elias–Fano Selection and Construction',['../eliasfano-selection-and-construction.html',1,'']]],
  ['and_20content_20identity_75',['Path spelling and content identity',['../md_docs_2file-lifecycle.html#path-spelling-and-content-identity',1,'']]],
  ['and_20declaration_20ownership_76',['Doxygen metadata and declaration ownership',['../md_docs_2doxygen.html',1,'']]],
  ['and_20decoding_20context_77',['4. Front coding and decoding context',['../md_docs_2design.html#autotoc_md4-front-coding-and-decoding-context',1,'']]],
  ['and_20durable_20continuation_78',['7. Coverage, contributions and durable continuation',['../md_docs_2rebuild.html#autotoc_md7-coverage-contributions-and-durable-continuation',1,'']]],
  ['and_20equality_79',['False borrows and equality',['../md_docs_2design.html#false-borrows-and-equality',1,'']]],
  ['and_20evaluation_20cost_20separate_80',['5. Navigation cost and evaluation cost separate',['../md_docs_2arrows.html#autotoc_md5-navigation-cost-and-evaluation-cost-separate',1,'']]],
  ['and_20exact_20layouts_81',['Contents and exact layouts',['../md_docs_2catalog.html#contents-and-exact-layouts',1,'']]],
  ['and_20fixed_20width_20values_82',['select15 and fixed-width values',['../md_docs_2design.html#select15-and-fixed-width-values',1,'']]],
  ['and_20framing_83',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['and_20garbage_20collection_84',['6. Reader acquisition and garbage collection',['../md_docs_2catalog.html#autotoc_md6-reader-acquisition-and-garbage-collection',1,'']]],
  ['and_20global_20rebuilding_85',['Strong deletes and global rebuilding',['../md_docs_2implementation.html#strong-deletes-and-global-rebuilding',1,'']]],
  ['and_20implementation_20boundary_86',['Pins integration and implementation boundary',['../md_docs_2durability.html#pins-integration-and-implementation-boundary',1,'']]],
  ['and_20its_20limits_87',['Anchored decoding and its limits',['../md_docs_2design.html#anchored-decoding-and-its-limits',1,'']]],
  ['and_20key_20policies_88',['Aggregate API and key policies',['../md_docs_2implementation.html#aggregate-api-and-key-policies',1,'']]],
  ['and_20limits_89',['and limits',['../eliasfano-selection-and-construction.html#rejected-prototypes-and-limits',1,'Rejected prototypes and limits'],['../packed-group-and-bitmap-rank-reductions.html#validation-and-limits',1,'Validation and limits']]],
  ['and_20live_20count_20checks_90',['Hash and live-count checks',['../md_docs_2rebuild.html#hash-and-live-count-checks',1,'']]],
  ['and_20live_20universe_20rebuilding_91',['7. Strong deletes and live-universe rebuilding',['../md_docs_2design.html#autotoc_md7-strong-deletes-and-live-universe-rebuilding',1,'']]],
  ['and_20math_92',['Markdown pages and math',['../md_docs_2doxygen.html#markdown-pages-and-math',1,'']]],
  ['and_20merge_20resumption_93',['and merge resumption',['../md_docs_2implementation.html#durability-and-merge-resumption',1,'Durability and merge resumption'],['../md_docs_2durability.html',1,'Durable publication and merge resumption']]],
  ['and_20merge_20work_94',['5. Redundant levels and merge work',['../md_docs_2design.html#autotoc_md5-redundant-levels-and-merge-work',1,'']]],
  ['and_20method_95',['Host and method',['../native-avx2-packed-rank-comparison.html#host-and-method',1,'']]],
  ['and_20multiplicity_96',['Logical key identity and multiplicity',['../md_docs_2arrows.html#logical-key-identity-and-multiplicity',1,'']]],
  ['and_20mutable_20selections_97',['Retention roots and mutable selections',['../md_docs_2catalog.html#retention-roots-and-mutable-selections',1,'']]],
  ['and_20names_98',['Objects and names',['../md_docs_2file-lifecycle.html#objects-and-names',1,'']]],
  ['and_20network_20admission_99',['SQLite catalog and network admission',['../md_docs_2implementation.html#sqlite-catalog-and-network-admission',1,'']]],
  ['and_20next_20contract_100',['7. Implementation boundary and next contract',['../md_docs_2arrows.html#autotoc_md7-implementation-boundary-and-next-contract',1,'']]],
  ['and_20offsets_101',['String compression and offsets',['../index.html#string-compression-and-offsets',1,'']]],
  ['and_20order_102',['1. One canonical identity and order',['../md_docs_2keys.html#autotoc_md1-one-canonical-identity-and-order',1,'']]],
  ['and_20ownership_103',['Blobs, worlds, and ownership',['../index.html#blobs-worlds-and-ownership',1,'']]],
  ['and_20packed_20rank_20comparison_104',['Full-vector and packed-rank comparison',['../md_bench_2rank__compare.html',1,'']]],
  ['and_20padding_105',['4. Bit lengths, units, and padding',['../md_docs_2keys.html#autotoc_md4-bit-lengths-units-and-padding',1,'']]],
  ['and_20pipeline_20performance_106',['Blob and pipeline performance',['../blob-and-pipeline-performance.html',1,'']]],
  ['and_20preserve_20the_20next_20generation_20s_20slack_107',['3. Trigger early and preserve the next generation&apos;s slack',['../md_docs_2rebuild.html#autotoc_md3-trigger-early-and-preserve-the-next-generations-slack',1,'']]],
  ['and_20publication_108',['Files, mappings and publication',['../md_docs_2file-lifecycle.html',1,'']]],
  ['and_20published_20state_109',['5. Ingestion state and published state',['../md_docs_2network-admission.html#autotoc_md5-ingestion-state-and-published-state',1,'']]],
  ['and_20query_20a_20blob_110',['Build and query a blob',['../index.html#build-and-query-a-blob',1,'']]],
  ['and_20rebuilding_20progress_111',['7. Checkpoints and rebuilding progress',['../md_docs_2catalog.html#autotoc_md7-checkpoints-and-rebuilding-progress',1,'']]],
  ['and_20recovery_112',['Acknowledgment, checkpoints and recovery',['../md_docs_2file-lifecycle.html#acknowledgment-checkpoints-and-recovery',1,'']]],
  ['and_20reductions_113',['Sources and reductions',['../native-avx2-packed-rank-comparison.html#sources-and-reductions',1,'']]],
  ['and_20remaining_20proof_20work_114',['7. Executable evidence and remaining proof work',['../md_docs_2sampling.html#autotoc_md7-executable-evidence-and-remaining-proof-work',1,'']]],
  ['and_20reproduction_115',['Validation and reproduction',['../eliasfano-selection-and-construction.html#validation-and-reproduction',1,'']]],
  ['and_20results_116',['Shared input and results',['../md_bench_2rank__compare__windows.html#shared-input-and-results',1,'']]],
  ['and_20resume_117',['Work that can stop and resume',['../index.html#work-that-can-stop-and-resume',1,'']]],
  ['and_20resumption_118',['Durability and resumption',['../md_docs_2design.html#durability-and-resumption',1,'']]],
  ['and_20run_119',['Build and run',['../everett-an-abstract-proof-core.html#build-and-run',1,'']]],
  ['and_20scan_20work_120',['4. Space and scan work',['../md_docs_2sampling.html#autotoc_md4-space-and-scan-work',1,'']]],
  ['and_20scheduling_20obligations_121',['3. Query bounds and scheduling obligations',['../md_docs_2network-admission.html#autotoc_md3-query-bounds-and-scheduling-obligations',1,'']]],
  ['and_20shared_20work_122',['6. Snapshots, saves, and shared work',['../md_docs_2design.html#autotoc_md6-snapshots-saves-and-shared-work',1,'']]],
  ['and_20sparse_20offsets_123',['Rank and sparse offsets',['../md_docs_2implementation.html#rank-and-sparse-offsets',1,'']]],
  ['and_20stringlike_20keys_124',['Sorts and stringlike keys',['../md_docs_2keys.html',1,'']]],
  ['and_20strong_20deletion_125',['6. Blobs, pins, checkpoints and strong deletion',['../md_docs_2arrows.html#autotoc_md6-blobs-pins-checkpoints-and-strong-deletion',1,'']]],
  ['and_20the_20choice_20of_20k_126',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['and_20the_20cult_20bitmap_20rank_127',['NEON reductions and the Cult bitmap rank',['../md_bench_2neon__cult__rank.html',1,'']]],
  ['and_20their_20roles_128',['11. References and their roles',['../md_docs_2design.html#autotoc_md11-references-and-their-roles',1,'']]],
  ['and_20transaction_20policy_129',['4. Connection and transaction policy',['../md_docs_2catalog.html#autotoc_md4-connection-and-transaction-policy',1,'']]],
  ['and_20trigger_130',['Generation state and trigger',['../md_docs_2design.html#generation-state-and-trigger',1,'']]],
  ['and_20type_20family_131',['Object envelopes, mappings and type family',['../md_docs_2implementation.html#object-envelopes-mappings-and-type-family',1,'']]],
  ['and_20validation_132',['and validation',['../md_bench_2rank__compare__windows.html#features-affinity-and-validation',1,'Features, affinity and validation'],['../md_bench_2neon__cult__rank.html#method-and-validation',1,'Method and validation']]],
  ['and_20verification_133',['and verification',['../md_docs_2implementation.html#build-and-verification',1,'Build and verification'],['../md__a_g_e_n_t_s.html#work-and-verification',1,'Work and verification']]],
  ['and_20verification_20boundary_134',['Axiom audit and verification boundary',['../everett-an-abstract-proof-core.html#axiom-audit-and-verification-boundary',1,'']]],
  ['api_20and_20key_20policies_135',['Aggregate API and key policies',['../md_docs_2implementation.html#aggregate-api-and-key-policies',1,'']]],
  ['append_136',['append',['../namespaceeverett_1_1profile__detail.html#aeaaf0159830d6d5bbd9a0d22e1ad7bb3',1,'everett::profile_detail::append()'],['../structeverett_1_1profile__borrowed__writer.html#a19f9f74fe5c201322df2f1984f165d1e',1,'everett::profile_borrowed_writer::append()'],['../structeverett_1_1reference__world.html#a009c0d70ad0efe5727c2789128b64069',1,'everett::reference_world::append()']]],
  ['append_5fbit_137',['append_bit',['../namespaceeverett_1_1profile__detail.html#a1da1b0de6f437ea3e3ed477e85b553e7',1,'everett::profile_detail']]],
  ['append_5fbyte_138',['append_byte',['../namespaceeverett_1_1profile__detail.html#a7f1e2f179a9d5b9f88b1ba1288b698b4',1,'everett::profile_detail']]],
  ['append_5fvarint_139',['append_varint',['../namespaceeverett_1_1front__detail.html#aaaac4bfe65001bf3bed1266f5a990b65',1,'everett::front_detail']]],
  ['applied_140',['applied',['../namespaceeverett.html#abdd0012244f6054f1fd40fe06a2f3a0baad8437d4bf608f79c1f0de5b5f54d31b',1,'everett']]],
  ['apply_141',['apply',['../structeverett_1_1partition__round.html#a343c5b9ae5f295cc0d9be6b8af07873c',1,'everett::partition_round']]],
  ['apply_20disjoint_20updates_142',['Fork a world and apply disjoint updates',['../index.html#fork-a-world-and-apply-disjoint-updates',1,'']]],
  ['are_20exact_20additive_20changes_20of_20state_20potential_143',['4. Fingerprints are exact additive changes of state potential',['../md_docs_2arrows.html#autotoc_md4-fingerprints-are-exact-additive-changes-of-state-potential',1,'']]],
  ['are_20not_20bytes_144',['8. Records are not bytes',['../md_docs_2rebuild.html#autotoc_md8-records-are-not-bytes',1,'']]],
  ['are_20not_20retention_20counts_145',['3. Contributions are not retention counts',['../md_docs_2catalog.html#autotoc_md3-contributions-are-not-retention-counts',1,'']]],
  ['are_20simplices_20merges_20compose_20adjacent_20segments_146',['2. Histories are simplices; merges compose adjacent segments',['../md_docs_2arrows.html#autotoc_md2-histories-are-simplices-merges-compose-adjacent-segments',1,'']]],
  ['arrows_2emd_147',['arrows.md',['../arrows_8md.html',1,'']]],
  ['assignments_148',['Next implementation assignments',['../md_docs_2implementation.html#next-implementation-assignments',1,'']]],
  ['assumptions_20mean_149',['What the assumptions mean',['../everett-an-abstract-proof-core.html#what-the-assumptions-mean',1,'']]],
  ['at_150',['at',['../structeverett_1_1bit__view.html#a13a55df6f40ec03b4fc0347c19005168',1,'everett::bit_view']]],
  ['at_20a_20finite_20cut_151',['Adopt at a finite cut',['../md_docs_2rebuild.html#adopt-at-a-finite-cut',1,'']]],
  ['audit_20and_20verification_20boundary_152',['Axiom audit and verification boundary',['../everett-an-abstract-proof-core.html#axiom-audit-and-verification-boundary',1,'']]],
  ['augmentation_20along_20one_20chain_153',['3. Per-level augmentation along one chain',['../md_docs_2sampling.html#autotoc_md3-per-level-augmentation-along-one-chain',1,'']]],
  ['available_154',['Replay while the foreground remains available',['../md_docs_2rebuild.html#replay-while-the-foreground-remains-available',1,'']]],
  ['avx2_20packed_20rank_20comparison_155',['Native AVX2 packed-rank comparison',['../native-avx2-packed-rank-comparison.html',1,'']]],
  ['axiom_20audit_20and_20verification_20boundary_156',['Axiom audit and verification boundary',['../everett-an-abstract-proof-core.html#axiom-audit-and-verification-boundary',1,'']]]
];
