var searchData=
[
  ['sample_5fcursor_0',['sample_cursor',['../structeverett_1_1sample__cursor.html',1,'everett']]],
  ['sample_5fcursor_3c_20p_2c_20mapped_5fblob_3c_20p_20_3e_20_3e_1',['sample_cursor&lt; P, mapped_blob&lt; P &gt; &gt;',['../structeverett_1_1sample__cursor.html',1,'everett']]],
  ['sample_5fcursor_3c_20p_2c_20profile_5fblob_3c_20p_20_3e_20_3e_2',['sample_cursor&lt; P, profile_blob&lt; P &gt; &gt;',['../structeverett_1_1sample__cursor.html',1,'everett']]],
  ['sample_5fcursor_3c_20p_2c_20target_20_3e_3',['sample_cursor&lt; P, Target &gt;',['../structeverett_1_1sample__cursor.html',1,'everett']]],
  ['sample_5fvalue_4',['sample_value',['../structeverett_1_1sample__value.html',1,'everett']]],
  ['sample_5fview_5',['sample_view',['../structeverett_1_1sample__view.html',1,'everett']]],
  ['sampling_5fwork_6',['sampling_work',['../structeverett_1_1sampling__work.html',1,'everett']]],
  ['scoped_5fborrowed_5fview_7',['scoped_borrowed_view',['../structeverett_1_1cola__detail_1_1scoped__borrowed__view.html',1,'everett::cola_detail']]],
  ['scoped_5fborrowed_5fview_3c_20profile_5fview_3c_20p_2c_20stream_5frole_3a_3aborrowed_20_3e_20_3e_8',['scoped_borrowed_view&lt; profile_view&lt; P, stream_role::borrowed &gt; &gt;',['../structeverett_1_1cola__detail_1_1scoped__borrowed__view_3_01profile__view_3_01_p_00_01stream__role_1_1borrowed_01_4_01_4.html',1,'everett::cola_detail']]],
  ['scoped_5fnative_5fview_9',['scoped_native_view',['../structeverett_1_1cola__detail_1_1scoped__native__view.html',1,'everett::cola_detail']]],
  ['scoped_5fnative_5fview_3c_20profile_5fview_3c_20p_2c_20stream_5frole_3a_3anative_20_3e_20_3e_10',['scoped_native_view&lt; profile_view&lt; P, stream_role::native &gt; &gt;',['../structeverett_1_1cola__detail_1_1scoped__native__view_3_01profile__view_3_01_p_00_01stream__role_1_1native_01_4_01_4.html',1,'everett::cola_detail']]],
  ['scoped_5fnative_5fview_3c_20sort_5fprofile_5fview_3c_20p_2c_20selector_20_3e_20_3e_11',['scoped_native_view&lt; sort_profile_view&lt; P, Selector &gt; &gt;',['../structeverett_1_1cola__detail_1_1scoped__native__view_3_01sort__profile__view_3_01_p_00_01_selector_01_4_01_4.html',1,'everett::cola_detail']]],
  ['sealed_5fmerge_5fextent_12',['sealed_merge_extent',['../structeverett_1_1sealed__merge__extent.html',1,'everett']]],
  ['secondary_5fspool_13',['secondary_spool',['../structeverett_1_1cola__detail_1_1secondary__spool.html',1,'everett::cola_detail']]],
  ['secondary_5fspool_3c_20posix_5findex_5fspool_5fops_20_3e_14',['secondary_spool&lt; posix_index_spool_ops &gt;',['../structeverett_1_1cola__detail_1_1secondary__spool.html',1,'everett::cola_detail']]],
  ['secondary_5fspool_3c_20spoolops_20_3e_15',['secondary_spool&lt; SpoolOps &gt;',['../structeverett_1_1cola__detail_1_1secondary__spool.html',1,'everett::cola_detail']]],
  ['session_16',['session',['../structeverett_1_1session.html',1,'everett']]],
  ['session_5fcancelled_17',['session_cancelled',['../structeverett_1_1session__cancelled.html',1,'everett']]],
  ['session_5fclosed_18',['session_closed',['../structeverett_1_1session__closed.html',1,'everett']]],
  ['session_5flimits_19',['session_limits',['../structeverett_1_1session__limits.html',1,'everett']]],
  ['session_5freservation_20',['session_reservation',['../structeverett_1_1session__reservation.html',1,'everett']]],
  ['shape_5fonly_21',['shape_only',['../structeverett_1_1profile__view_1_1shape__only.html',1,'everett::profile_view']]],
  ['slot_22',['slot',['../structeverett_1_1catalog__bindings_1_1slot.html',1,'everett::catalog_bindings']]],
  ['snapshot_5ftype_23',['snapshot_type',['../structeverett_1_1nursery__map_1_1snapshot__type.html',1,'everett::nursery_map&lt; Key, Value, Compare &gt;::snapshot_type'],['../structeverett_1_1transaction_1_1snapshot__type.html',1,'everett::transaction&lt; Core &gt;::snapshot_type']]],
  ['sort_24',['sort',['../structeverett_1_1sort.html',1,'everett']]],
  ['sort_5fbit_5freader_25',['sort_bit_reader',['../structeverett_1_1sort__bit__reader.html',1,'everett']]],
  ['sort_5fbit_5fwriter_26',['sort_bit_writer',['../structeverett_1_1sort__bit__writer.html',1,'everett']]],
  ['sort_5fcodec_27',['sort_codec',['../structeverett_1_1sort__codec.html',1,'everett']]],
  ['sort_5fcodec_3c_20unsorted_3c_20std_3a_3aoptional_3c_20std_3a_3astring_20_3e_20_3e_20_3e_28',['sort_codec&lt; unsorted&lt; std::optional&lt; std::string &gt; &gt; &gt;',['../structeverett_1_1sort__codec_3_01unsorted_3_01std_1_1optional_3_01std_1_1string_01_4_01_4_01_4.html',1,'everett']]],
  ['sort_5fcodec_3c_20unsorted_3c_20std_3a_3astring_20_3e_20_3e_29',['sort_codec&lt; unsorted&lt; std::string &gt; &gt;',['../structeverett_1_1sort__codec_3_01unsorted_3_01std_1_1string_01_4_01_4.html',1,'everett']]],
  ['sort_5ffile_5fruntime_5fstorage_30',['sort_file_runtime_storage',['../structeverett_1_1sort__file__runtime__storage.html',1,'everett']]],
  ['sort_5fkey_5ftransport_31',['sort_key_transport',['../structeverett_1_1sort__key__transport.html',1,'everett']]],
  ['sort_5flist_32',['sort_list',['../structeverett_1_1sort__list.html',1,'everett']]],
  ['sort_5fprofile_5fadaptive_5fmerge_33',['sort_profile_adaptive_merge',['../structeverett_1_1sort__profile__adaptive__merge.html',1,'everett']]],
  ['sort_5fprofile_5fadaptive_5fmerge_3c_20p_2c_20native_5ftype_2c_20compose_2c_20selector_2c_20fileops_2c_20native_5fstream_5ffactory_20_3e_34',['sort_profile_adaptive_merge&lt; P, native_type, Compose, Selector, FileOps, native_stream_factory &gt;',['../structeverett_1_1sort__profile__adaptive__merge.html',1,'everett']]],
  ['sort_5fprofile_5fadaptive_5fwriter_35',['sort_profile_adaptive_writer',['../structeverett_1_1sort__profile__adaptive__writer.html',1,'everett']]],
  ['sort_5fprofile_5fadaptive_5fwriter_3c_20p_2c_20selector_2c_20fileops_2c_20native_5fstream_5ffactory_20_3e_36',['sort_profile_adaptive_writer&lt; P, Selector, FileOps, native_stream_factory &gt;',['../structeverett_1_1sort__profile__adaptive__writer.html',1,'everett']]],
  ['sort_5fprofile_5farray_37',['sort_profile_array',['../structeverett_1_1sort__profile__array.html',1,'everett']]],
  ['sort_5fprofile_5fcursor_38',['sort_profile_cursor',['../structeverett_1_1sort__profile__cursor.html',1,'everett']]],
  ['sort_5fprofile_5ffamily_39',['sort_profile_family',['../structeverett_1_1sort__profile__family.html',1,'everett']]],
  ['sort_5fprofile_5ffile_5fmerge_40',['sort_profile_file_merge',['../structeverett_1_1sort__profile__file__merge.html',1,'everett']]],
  ['sort_5fprofile_5ffile_5fwriter_41',['sort_profile_file_writer',['../structeverett_1_1sort__profile__file__writer.html',1,'everett']]],
  ['sort_5fprofile_5ffile_5fwriter_3c_20p_2c_20selector_2c_20ops_20_3e_42',['sort_profile_file_writer&lt; P, Selector, Ops &gt;',['../structeverett_1_1sort__profile__file__writer.html',1,'everett']]],
  ['sort_5fprofile_5ffile_5fwriter_3c_20p_2c_20typename_20native_3a_3astream_5ffamily_3a_3aselector_5ftype_2c_20posix_5fobject_5fops_20_3e_43',['sort_profile_file_writer&lt; P, typename Native::stream_family::selector_type, posix_object_ops &gt;',['../structeverett_1_1sort__profile__file__writer.html',1,'everett']]],
  ['sort_5fprofile_5fframe_44',['sort_profile_frame',['../structeverett_1_1sort__profile__frame.html',1,'everett']]],
  ['sort_5fprofile_5fkey_45',['sort_profile_key',['../structeverett_1_1sort__profile__key.html',1,'everett']]],
  ['sort_5fprofile_5fkey_3c_20fc_5fbit_5fkey_3c_20c_20_3e_20_3e_46',['sort_profile_key&lt; fc_bit_key&lt; C &gt; &gt;',['../structeverett_1_1sort__profile__key_3_01fc__bit__key_3_01_c_01_4_01_4.html',1,'everett']]],
  ['sort_5fprofile_5fkey_3c_20fc_5fstring_5fkey_3c_20c_20_3e_20_3e_47',['sort_profile_key&lt; fc_string_key&lt; C &gt; &gt;',['../structeverett_1_1sort__profile__key_3_01fc__string__key_3_01_c_01_4_01_4.html',1,'everett']]],
  ['sort_5fprofile_5fkey_3c_20raw_5fstring_5fkey_3c_20c_20_3e_20_3e_48',['sort_profile_key&lt; raw_string_key&lt; C &gt; &gt;',['../structeverett_1_1sort__profile__key_3_01raw__string__key_3_01_c_01_4_01_4.html',1,'everett']]],
  ['sort_5fprofile_5fkey_3c_20unsigned_5fkey_3c_20n_20_3e_20_3e_49',['sort_profile_key&lt; unsigned_key&lt; N &gt; &gt;',['../structeverett_1_1sort__profile__key_3_01unsigned__key_3_01_n_01_4_01_4.html',1,'everett']]],
  ['sort_5fprofile_5fmerge_5fbuilder_50',['sort_profile_merge_builder',['../structeverett_1_1sort__profile__merge__builder.html',1,'everett']]],
  ['sort_5fprofile_5fmerge_5fbuilder_3c_20p_2c_20native_2c_20compose_2c_20selector_2c_20output_5fref_20_3e_51',['sort_profile_merge_builder&lt; P, Native, Compose, Selector, output_ref &gt;',['../structeverett_1_1sort__profile__merge__builder.html',1,'everett']]],
  ['sort_5fprofile_5fmerge_5fbuilder_3c_20p_2c_20native_5ftype_2c_20compose_2c_20selector_2c_20output_5fref_20_3e_52',['sort_profile_merge_builder&lt; P, native_type, Compose, Selector, output_ref &gt;',['../structeverett_1_1sort__profile__merge__builder.html',1,'everett']]],
  ['sort_5fprofile_5fmerge_5fbuilder_3c_20p_2c_20sort_5fprofile_5farray_3c_20p_20_3e_2c_20replace_5fnative_5fvalue_2c_20typename_20native_3a_3astream_5ffamily_3a_3aselector_5ftype_2c_20sort_5fprofile_5fdetail_3a_3afile_5foutput_5fref_3c_20p_2c_20typename_20native_3a_3astream_5ffamily_3a_3aselector_5ftype_2c_20posix_5fobject_5fops_20_3e_20_3e_53',['sort_profile_merge_builder&lt; P, sort_profile_array&lt; P &gt;, replace_native_value, typename Native::stream_family::selector_type, sort_profile_detail::file_output_ref&lt; P, typename Native::stream_family::selector_type, posix_object_ops &gt; &gt;',['../structeverett_1_1sort__profile__merge__builder.html',1,'everett']]],
  ['sort_5fprofile_5fpayload_54',['sort_profile_payload',['../structeverett_1_1sort__profile__payload.html',1,'everett']]],
  ['sort_5fprofile_5fview_55',['sort_profile_view',['../structeverett_1_1sort__profile__view.html',1,'everett']]],
  ['sort_5fprofile_5fview_3c_20p_2c_20registry_5fselector_3c_20typename_20p_3a_3aregistry_5ftype_20_3e_20_3e_56',['sort_profile_view&lt; P, registry_selector&lt; typename P::registry_type &gt; &gt;',['../structeverett_1_1sort__profile__view.html',1,'everett']]],
  ['sort_5fprofile_5fwriter_57',['sort_profile_writer',['../structeverett_1_1sort__profile__writer.html',1,'everett']]],
  ['sort_5fprofile_5fwriter_3c_20p_2c_20typename_20native_3a_3astream_5ffamily_3a_3aselector_5ftype_20_3e_58',['sort_profile_writer&lt; P, typename Native::stream_family::selector_type &gt;',['../structeverett_1_1sort__profile__writer.html',1,'everett']]],
  ['sort_5frecord_5fcontrol_59',['sort_record_control',['../structeverett_1_1sort__record__control.html',1,'everett']]],
  ['sort_5frecord_5freader_60',['sort_record_reader',['../structeverett_1_1sort__record__reader.html',1,'everett']]],
  ['sort_5frecord_5fstate_61',['sort_record_state',['../structeverett_1_1sort__record__state.html',1,'everett']]],
  ['sort_5frecord_5fwriter_62',['sort_record_writer',['../structeverett_1_1sort__record__writer.html',1,'everett']]],
  ['sort_5fruntime_5fcontext_63',['sort_runtime_context',['../structeverett_1_1sort__runtime__context.html',1,'everett']]],
  ['sort_5fruntime_5ffamily_64',['sort_runtime_family',['../structeverett_1_1sort__runtime__family.html',1,'everett']]],
  ['sort_5fruntime_5fnative_65',['sort_runtime_native',['../structeverett_1_1sort__runtime__native.html',1,'everett']]],
  ['sort_5fruntime_5fstorage_66',['sort_runtime_storage',['../structeverett_1_1sort__runtime__storage.html',1,'everett']]],
  ['sort_5fruntime_5fstorage_3c_20p_2c_20registry_5fselector_3c_20typename_20p_3a_3aregistry_5ftype_20_3e_20_3e_67',['sort_runtime_storage&lt; P, registry_selector&lt; typename P::registry_type &gt; &gt;',['../structeverett_1_1sort__runtime__storage.html',1,'everett']]],
  ['sort_5fsemantics_68',['sort_semantics',['../structeverett_1_1sort__semantics.html',1,'everett']]],
  ['sort_5fsemantics_3c_20unsorted_3c_20std_3a_3aoptional_3c_20std_3a_3astring_20_3e_20_3e_20_3e_69',['sort_semantics&lt; unsorted&lt; std::optional&lt; std::string &gt; &gt; &gt;',['../structeverett_1_1sort__semantics_3_01unsorted_3_01std_1_1optional_3_01std_1_1string_01_4_01_4_01_4.html',1,'everett']]],
  ['sort_5fundefined_70',['sort_undefined',['../structeverett_1_1sort__undefined.html',1,'everett']]],
  ['sorts_71',['sorts',['../structeverett_1_1registry__detail_1_1sorts.html',1,'everett::registry_detail']]],
  ['source_72',['source',['../structeverett_1_1typed__detail_1_1native__sweep_1_1source.html',1,'everett::typed_detail::native_sweep']]],
  ['span_73',['span',['../structeverett_1_1native__merge__detail_1_1encoded__source_1_1span.html',1,'everett::native_merge_detail::encoded_source']]],
  ['sqlite_5fcatalog_74',['sqlite_catalog',['../structeverett_1_1sqlite__catalog.html',1,'everett']]],
  ['sqlite_5fcatalog_3c_20p_2c_20sqlite_5fcatalog_5fops_20_3e_75',['sqlite_catalog&lt; P, sqlite_catalog_ops &gt;',['../structeverett_1_1sqlite__catalog.html',1,'everett']]],
  ['sqlite_5fcatalog_3c_20policy_5ftype_2c_20sqlite_5fcatalog_5fops_20_3e_76',['sqlite_catalog&lt; policy_type, sqlite_catalog_ops &gt;',['../structeverett_1_1sqlite__catalog.html',1,'everett']]],
  ['sqlite_5fcatalog_5fops_77',['sqlite_catalog_ops',['../structeverett_1_1sqlite__catalog__ops.html',1,'everett']]],
  ['stage_78',['stage',['../structeverett_1_1transaction_1_1stage.html',1,'everett::transaction']]],
  ['state_79',['state',['../structeverett_1_1cola__runtime__snapshot_1_1state.html',1,'everett::cola_runtime_snapshot&lt; P &gt;::state'],['../structeverett_1_1output__budget_1_1state.html',1,'everett::output_budget::state'],['../structeverett_1_1pin__set_1_1state.html',1,'everett::pin_set&lt; T, A &gt;::state'],['../structeverett_1_1redundant__snapshot_1_1state.html',1,'everett::redundant_snapshot&lt; P, Storage &gt;::state'],['../structeverett_1_1reference__world_1_1state.html',1,'everett::reference_world&lt; V, A, H &gt;::state'],['../structeverett_1_1typed__world_1_1state.html',1,'everett::typed_world&lt; P, A, Family &gt;::state']]],
  ['statement_80',['statement',['../structeverett_1_1catalog__detail_1_1statement.html',1,'everett::catalog_detail']]],
  ['states_81',['states',['../structeverett_1_1sort__codec__detail_1_1states.html',1,'everett::sort_codec_detail']]],
  ['states_3c_20registry_5fdetail_3a_3asorts_3c_20s_2e_2e_2e_20_3e_20_3e_82',['states&lt; registry_detail::sorts&lt; S... &gt; &gt;',['../structeverett_1_1sort__codec__detail_1_1states_3_01registry__detail_1_1sorts_3_01_s_8_8_8_01_4_01_4.html',1,'everett::sort_codec_detail']]],
  ['states_3c_20typenameregistry_5fdetail_3a_3ainfo_3c_20registry_20_3e_3a_3aleaves_20_3e_83',['states&lt; typenameregistry_detail::info&lt; Registry &gt;::leaves &gt;',['../structeverett_1_1sort__codec__detail_1_1states.html',1,'everett::sort_codec_detail']]],
  ['statistics_84',['statistics',['../structeverett_1_1nursery__map_1_1statistics.html',1,'everett::nursery_map']]],
  ['storage_5fpolicy_85',['storage_policy',['../structeverett_1_1storage__policy.html',1,'everett']]],
  ['stored_5fruntime_86',['stored_runtime',['../structeverett_1_1stored__runtime.html',1,'everett']]],
  ['stored_5fworld_87',['stored_world',['../structeverett_1_1stored__world.html',1,'everett']]],
  ['stored_5fworld_3c_20typed_5fworld_5ftype_20_3e_88',['stored_world&lt; typed_world_type &gt;',['../structeverett_1_1stored__world.html',1,'everett']]],
  ['string_5fvalue_89',['string_value',['../structeverett_1_1string__value.html',1,'everett']]]
];
