var searchData=
[
  ['a_20category_20chosen_20per_20key_0',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['abstract_20proof_20core_1',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['admitting_20sorted_20blobs_20from_20peers_2',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['advancement_3',['Specializing cursor advancement',['../md_bench_2sample__advance.html',1,'']]],
  ['after_20bit_20arithmetic_20cleanup_4',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['after_20the_20rank_20and_20elias–fano_20refactor_5',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['an_20abstract_20proof_20core_6',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['an_20immutable_20catalog_20chain_7',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['and_20background_20work_8',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['and_20bitmap_20rank_20reductions_9',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['and_20construction_10',['Elias–Fano Selection and Construction',['../eliasfano-selection-and-construction.html',1,'']]],
  ['and_20declaration_20ownership_11',['Doxygen metadata and declaration ownership',['../md_docs_2doxygen.html',1,'']]],
  ['and_20elias–fano_20refactor_12',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['and_20encoder_20reuse_13',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['and_20exact_20query_20roots_14',['Mapped blobs and exact query roots',['../mapped-blobs-and-exact-query-roots.html',1,'']]],
  ['and_20framed_20output_15',['Native merge frontiers and framed output',['../native-merge-frontiers-and-framed-output.html',1,'']]],
  ['and_20framing_16',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['and_20merge_20resumption_17',['Durable publication and merge resumption',['../md_docs_2durability.html',1,'']]],
  ['and_20merging_18',['Incremental native writing and merging',['../md_docs_2native-merges.html',1,'']]],
  ['and_20packed_20rank_20comparison_19',['Full-vector and packed-rank comparison',['../md_bench_2rank__compare.html',1,'']]],
  ['and_20pipeline_20performance_20',['Blob and pipeline performance',['../blob-and-pipeline-performance.html',1,'']]],
  ['and_20publication_21',['Files, mappings and publication',['../md_docs_2file-lifecycle.html',1,'']]],
  ['and_20reservations_22',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['and_20stringlike_20keys_23',['Sorts and stringlike keys',['../md_docs_2keys.html',1,'']]],
  ['and_20the_20choice_20of_20k_24',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['and_20the_20cult_20bitmap_20rank_25',['NEON reductions and the Cult bitmap rank',['../md_bench_2neon__cult__rank.html',1,'']]],
  ['arithmetic_20cleanup_26',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['avx2_20packed_20rank_20comparison_27',['Native AVX2 packed-rank comparison',['../native-avx2-packed-rank-comparison.html',1,'']]]
];
