var searchData=
[
  ['rank_0',['rank',['../md_bench_2neon__bitmap__rank.html',1,'NEON reductions and the Bitmap512 rank'],['../stored-spacers-in-complete-bitmap-rank.html',1,'Stored spacers in complete bitmap rank']]],
  ['rank_20and_20elias–fano_20refactor_1',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['rank_20comparison_2',['rank comparison',['../md_bench_2rank__compare.html',1,'Full-vector and packed-rank comparison'],['../native-avx2-packed-rank-comparison.html',1,'Native AVX2 packed-rank comparison'],['../md_bench_2rank__compare__windows.html',1,'Native Windows packed-rank comparison']]],
  ['rank_20experiment_3',['Collision bitmap and rank experiment',['../collision-bitmap-and-rank-experiment.html',1,'']]],
  ['rank_20prefixes_4',['Intel paths for bounded 512-bit rank prefixes',['../intel-paths-for-bounded-512-bit-rank-prefixes.html',1,'']]],
  ['rank_20reductions_5',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['rank_20without_20cached_20totals_6',['Bounded rank without cached totals',['../bounded-rank-without-cached-totals.html',1,'']]],
  ['rank_3a_20checked_20alternatives_7',['Temporary collision rank: checked alternatives',['../temporary-collision-rank-checked-alternatives.html',1,'']]],
  ['rebuilding_8',['Strong deletion by incremental rebuilding',['../md_docs_2rebuild.html',1,'']]],
  ['rebuilding_20replacement_20tables_9',['Rebuilding replacement tables',['../rebuilding-replacement-tables.html',1,'']]],
  ['records_10',['records',['../sort-owned-bit-records.html',1,'Sort-owned bit records'],['../sort-owned-native-records.html',1,'Sort-owned native records']]],
  ['records_20in_20the_20redundant_20runtime_11',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['reductions_12',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['reductions_20and_20the_20bitmap512_20rank_13',['NEON reductions and the Bitmap512 rank',['../md_bench_2neon__bitmap__rank.html',1,'']]],
  ['redundant_20cola_20execution_14',['Redundant COLA execution',['../redundant-cola-execution.html',1,'']]],
  ['redundant_20runtime_15',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['refactor_16',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['replacement_20tables_17',['Rebuilding replacement tables',['../rebuilding-replacement-tables.html',1,'']]],
  ['reservations_18',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['results_19',['Matched fixed-key and KV03 Metal results',['../matched-fixed-key-and-kv03-metal-results.html',1,'']]],
  ['resumption_20',['resumption',['../md_docs_2durability.html',1,'Durable publication and merge resumption'],['../md_docs_2merge-resumption.html',1,'Merge resumption']]],
  ['retained_20select_20measurements_21',['Retained select measurements',['../retained-select-measurements.html',1,'']]],
  ['reuse_22',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['reusing_20borrowed_20key_20prefixes_23',['Reusing borrowed-key prefixes',['../md_bench_2borrowed__prefix.html',1,'']]],
  ['reusing_20completed_20native_20merges_24',['Reusing completed native merges',['../reusing-completed-native-merges.html',1,'']]],
  ['reusing_20native_20key_20prefixes_25',['Reusing native-key prefixes',['../md_bench_2native__prefix.html',1,'']]],
  ['roots_26',['roots',['../mapped-blobs-and-exact-query-roots.html',1,'Mapped blobs and exact query roots'],['../saving-and-merging-mapped-cola-roots.html',1,'Saving and merging mapped COLA roots']]],
  ['roots_20and_20reservations_27',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['runtime_28',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['runtime_20frontier_29',['Persisting a runtime frontier',['../persisting-a-runtime-frontier.html',1,'']]]
];
