var searchData=
[
  ['packed_20group_20and_20bitmap_20rank_20reductions_0',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['packed_20rank_20comparison_1',['packed rank comparison',['../md_bench_2rank__compare.html',1,'Full-vector and packed-rank comparison'],['../native-avx2-packed-rank-comparison.html',1,'Native AVX2 packed-rank comparison'],['../md_bench_2rank__compare__windows.html',1,'Native Windows packed-rank comparison']]],
  ['pairs_2',['COLA scheduling with immutable pairs',['../cola-scheduling-with-immutable-pairs.html',1,'']]],
  ['paths_20for_20bounded_20512_20bit_20rank_20prefixes_3',['Intel paths for bounded 512-bit rank prefixes',['../intel-paths-for-bounded-512-bit-rank-prefixes.html',1,'']]],
  ['paths_20in_20complete_20queries_4',['Cold exception paths in complete queries',['../cold-exception-paths-in-complete-queries.html',1,'']]],
  ['payload_20sharing_5',['COLA Borrowed Payload Sharing',['../cola-borrowed-payload-sharing.html',1,'']]],
  ['peers_6',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['per_20key_7',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['performance_8',['Blob and pipeline performance',['../blob-and-pipeline-performance.html',1,'']]],
  ['persistent_20sqlite_20roots_20and_20reservations_9',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['persistent_20storage_10',['Everett: Persistent Storage',['../index.html',1,'']]],
  ['persistent_20timeline_11',['Streaming a table into a persistent timeline',['../md_docs_2streamed-timeline.html',1,'']]],
  ['persisting_20a_20runtime_20frontier_12',['Persisting a runtime frontier',['../persisting-a-runtime-frontier.html',1,'']]],
  ['pins_20and_20background_20work_13',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['pipeline_20performance_14',['Blob and pipeline performance',['../blob-and-pipeline-performance.html',1,'']]],
  ['planning_15',['Optional fused GPU output planning',['../optional-fused-gpu-output-planning.html',1,'']]],
  ['portability_20check_16',['COLA Linux Portability Check',['../cola-linux-portability-check.html',1,'']]],
  ['prefix_20tree_20experiment_17',['Optional tiled prefix-tree experiment',['../optional-tiled-prefix-tree-experiment.html',1,'']]],
  ['prefixes_18',['prefixes',['../complete-queries-with-absolute-block-prefixes.html',1,'Complete queries with absolute block prefixes'],['../intel-paths-for-bounded-512-bit-rank-prefixes.html',1,'Intel paths for bounded 512-bit rank prefixes'],['../md_bench_2borrowed__prefix.html',1,'Reusing borrowed-key prefixes'],['../md_bench_2native__prefix.html',1,'Reusing native-key prefixes']]],
  ['prefixes_20bit_20copies_20and_20framing_19',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['preparation_20',['Publication preparation',['../publication-preparation.html',1,'']]],
  ['prepared_20chain_20queries_21',['Complete prepared-chain queries',['../md_bench_2query__chain.html',1,'']]],
  ['profile_20count_20decoding_22',['Small bit-profile count decoding',['../md_bench_2small__count.html',1,'']]],
  ['proof_20core_23',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['publication_24',['Files, mappings and publication',['../md_docs_2file-lifecycle.html',1,'']]],
  ['publication_20and_20merge_20resumption_25',['Durable publication and merge resumption',['../md_docs_2durability.html',1,'']]],
  ['publication_20preparation_26',['Publication preparation',['../publication-preparation.html',1,'']]]
];
