var searchData=
[
  ['same_20offsets_0',['Select alternatives on the same offsets',['../select-alternatives-on-the-same-offsets.html',1,'']]],
  ['sampling_20comparisons_20and_20encoder_20reuse_1',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['sampling_20groups_20and_20the_20choice_20of_20k_2',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['saving_20and_20merging_20mapped_20cola_20roots_3',['Saving and merging mapped COLA roots',['../saving-and-merging-mapped-cola-roots.html',1,'']]],
  ['scanning_20a_20table_4',['Scanning a table',['../scanning-a-table.html',1,'']]],
  ['scheduling_20with_20immutable_20pairs_5',['COLA scheduling with immutable pairs',['../cola-scheduling-with-immutable-pairs.html',1,'']]],
  ['sealing_6',['Immutable object sealing',['../immutable-object-sealing.html',1,'']]],
  ['search_7',['Bounded fixed-key search',['../bounded-fixed-key-search.html',1,'']]],
  ['search_20offset_20choices_8',['Whole-search offset choices',['../whole-search-offset-choices.html',1,'']]],
  ['searches_9',['Offset representations in complete searches',['../offset-representations-in-complete-searches.html',1,'']]],
  ['select_20alternatives_20on_20the_20same_20offsets_10',['Select alternatives on the same offsets',['../select-alternatives-on-the-same-offsets.html',1,'']]],
  ['select_20measurements_11',['Retained select measurements',['../retained-select-measurements.html',1,'']]],
  ['selection_20and_20construction_12',['Elias–Fano Selection and Construction',['../eliasfano-selection-and-construction.html',1,'']]],
  ['selection_20on_20actual_20file_20directories_13',['Offset selection on actual file directories',['../offset-selection-on-actual-file-directories.html',1,'']]],
  ['session_14',['Connecting to a named session',['../connecting-to-a-named-session.html',1,'']]],
  ['session_20for_20immutable_20worlds_15',['A mutable session for immutable worlds',['../a-mutable-session-for-immutable-worlds.html',1,'']]],
  ['shader_20toolchain_16',['Everett shader toolchain',['../everett-shader-toolchain.html',1,'']]],
  ['shared_20navigation_20views_17',['Owning queries with shared navigation views',['../md_bench_2shared__query.html',1,'']]],
  ['sharing_18',['COLA Borrowed Payload Sharing',['../cola-borrowed-payload-sharing.html',1,'']]],
  ['small_20bit_20profile_20count_20decoding_19',['Small bit-profile count decoding',['../md_bench_2small__count.html',1,'']]],
  ['small_20native_20merge_20outputs_20',['Small native merge outputs',['../small-native-merge-outputs.html',1,'']]],
  ['sort_20owned_20bit_20records_21',['Sort-owned bit records',['../sort-owned-bit-records.html',1,'']]],
  ['sort_20owned_20native_20files_22',['Streaming sort-owned native files',['../streaming-sort-owned-native-files.html',1,'']]],
  ['sort_20owned_20native_20records_23',['Sort-owned native records',['../sort-owned-native-records.html',1,'']]],
  ['sort_20owned_20records_20in_20the_20redundant_20runtime_24',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['sorted_20blobs_20from_20peers_25',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['sorts_20and_20stringlike_20keys_26',['Sorts and stringlike keys',['../md_docs_2keys.html',1,'']]],
  ['space_27',['Complete Byte/Bit File Space',['../complete-bytebit-file-space.html',1,'']]],
  ['space_20accounting_28',['Space accounting',['../space-accounting.html',1,'']]],
  ['space_20results_29',['Complete Byte/Bit Space Results',['../complete-bytebit-space-results.html',1,'']]],
  ['space_20tables_30',['Generated Space Tables',['../generated-space-tables.html',1,'']]],
  ['spacers_20in_20complete_20bitmap_20rank_31',['Stored spacers in complete bitmap rank',['../stored-spacers-in-complete-bitmap-rank.html',1,'']]],
  ['span_20descriptors_32',['Compact native-merge span descriptors',['../compact-native-merge-span-descriptors.html',1,'']]],
  ['specializing_20cursor_20advancement_33',['Specializing cursor advancement',['../md_bench_2sample__advance.html',1,'']]],
  ['sqlite_20catalog_20for_20worlds_20pins_20and_20background_20work_34',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['sqlite_20roots_20and_20reservations_35',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['state_36',['state',['../md_bench_2query__compare.html',1,'Complete queries with comparison state'],['../md_docs_2comparison-fc.html',1,'Front coding with comparison state']]],
  ['status_37',['Everett implementation status',['../md_docs_2implementation.html',1,'']]],
  ['storage_38',['Everett: Persistent Storage',['../index.html',1,'']]],
  ['stored_20spacers_20in_20complete_20bitmap_20rank_39',['Stored spacers in complete bitmap rank',['../stored-spacers-in-complete-bitmap-rank.html',1,'']]],
  ['streaming_20a_20fractional_20index_20chain_20to_20disk_40',['Streaming a fractional-index chain to disk',['../md_docs_2file-indexes.html',1,'']]],
  ['streaming_20a_20table_20into_20a_20persistent_20timeline_41',['Streaming a table into a persistent timeline',['../md_docs_2streamed-timeline.html',1,'']]],
  ['streaming_20fractional_20indexes_42',['Streaming fractional indexes',['../streaming-fractional-indexes.html',1,'']]],
  ['streaming_20sort_20owned_20native_20files_43',['Streaming sort-owned native files',['../streaming-sort-owned-native-files.html',1,'']]],
  ['string_20tables_44',['Byte String Tables',['../byte-string-tables.html',1,'']]],
  ['stringlike_20keys_45',['Sorts and stringlike keys',['../md_docs_2keys.html',1,'']]],
  ['strong_20deletion_20by_20incremental_20rebuilding_46',['Strong deletion by incremental rebuilding',['../md_docs_2rebuild.html',1,'']]]
];
