var searchData=
[
  ['a_20category_20chosen_20per_20key_0',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['a_20cola_20merge_1',['Building a COLA merge',['../building-a-cola-merge.html',1,'']]],
  ['a_20fractional_20index_20chain_20to_20disk_2',['Streaming a fractional-index chain to disk',['../md_docs_2file-indexes.html',1,'']]],
  ['a_20mutable_20session_20for_20immutable_20worlds_3',['A mutable session for immutable worlds',['../a-mutable-session-for-immutable-worlds.html',1,'']]],
  ['a_20named_20session_4',['Connecting to a named session',['../connecting-to-a-named-session.html',1,'']]],
  ['a_20runtime_20frontier_5',['Persisting a runtime frontier',['../persisting-a-runtime-frontier.html',1,'']]],
  ['a_20table_6',['Scanning a table',['../scanning-a-table.html',1,'']]],
  ['a_20table_20into_20a_20persistent_20timeline_7',['Streaming a table into a persistent timeline',['../md_docs_2streamed-timeline.html',1,'']]],
  ['absolute_20block_20prefixes_8',['Complete queries with absolute block prefixes',['../complete-queries-with-absolute-block-prefixes.html',1,'']]],
  ['abstract_20proof_20core_9',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['accounting_10',['Space accounting',['../space-accounting.html',1,'']]],
  ['adaptive_20fractional_20index_20output_11',['Adaptive fractional-index output',['../adaptive-fractional-index-output.html',1,'']]],
  ['adaptive_20native_20and_20fractional_20index_20output_12',['Adaptive native and fractional-index output',['../adaptive-native-and-fractional-index-output.html',1,'']]],
  ['admitting_20sorted_20blobs_20from_20peers_13',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['advancement_14',['Specializing cursor advancement',['../md_bench_2sample__advance.html',1,'']]],
  ['after_20bit_20arithmetic_20cleanup_15',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['after_20the_20rank_20and_20elias–fano_20refactor_16',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['alternatives_17',['Temporary collision rank: checked alternatives',['../temporary-collision-rank-checked-alternatives.html',1,'']]],
  ['an_20abstract_20proof_20core_18',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['an_20immutable_20catalog_20chain_19',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['and_20background_20work_20',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['and_20bitmap_20rank_20reductions_21',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['and_20byte_20native_20merges_22',['Matched CPU bit and byte native merges',['../matched-cpu-bit-and-byte-native-merges.html',1,'']]],
  ['and_20complete_20coverage_20cleanup_23',['Conservative tombstones and complete-coverage cleanup',['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'']]],
  ['and_20construction_24',['Elias–Fano Selection and Construction',['../eliasfano-selection-and-construction.html',1,'']]],
  ['and_20contributions_25',['Typed worlds and contributions',['../typed-worlds-and-contributions.html',1,'']]],
  ['and_20declaration_20ownership_26',['Doxygen metadata and declaration ownership',['../md_docs_2doxygen.html',1,'']]],
  ['and_20elias–fano_20refactor_27',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['and_20encoder_20reuse_28',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['and_20exact_20query_20roots_29',['Mapped blobs and exact query roots',['../mapped-blobs-and-exact-query-roots.html',1,'']]],
  ['and_20fractional_20index_20output_30',['Adaptive native and fractional-index output',['../adaptive-native-and-fractional-index-output.html',1,'']]],
  ['and_20framed_20output_31',['Native merge frontiers and framed output',['../native-merge-frontiers-and-framed-output.html',1,'']]],
  ['and_20framing_32',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['and_20front_20coded_20metal_20merges_33',['Matched fixed-key and front-coded Metal merges',['../matched-fixed-key-and-front-coded-metal-merges.html',1,'']]],
  ['and_20kv03_20metal_20results_34',['Matched fixed-key and KV03 Metal results',['../matched-fixed-key-and-kv03-metal-results.html',1,'']]],
  ['and_20mapped_20queries_35',['COLA indexes and mapped queries',['../cola-indexes-and-mapped-queries.html',1,'']]],
  ['and_20merge_20resumption_36',['Durable publication and merge resumption',['../md_docs_2durability.html',1,'']]],
  ['and_20merging_37',['Incremental native writing and merging',['../md_docs_2native-merges.html',1,'']]],
  ['and_20merging_20mapped_20cola_20roots_38',['Saving and merging mapped COLA roots',['../saving-and-merging-mapped-cola-roots.html',1,'']]],
  ['and_20output_39',['Optional GPU merge: direct compressed input and output',['../optional-gpu-merge-direct-compressed-input-and-output.html',1,'']]],
  ['and_20packed_20rank_20comparison_40',['Full-vector and packed-rank comparison',['../md_bench_2rank__compare.html',1,'']]],
  ['and_20pipeline_20performance_41',['Blob and pipeline performance',['../blob-and-pipeline-performance.html',1,'']]],
  ['and_20private_20nurseries_42',['Transactions and private nurseries',['../transactions-and-private-nurseries.html',1,'']]],
  ['and_20publication_43',['Files, mappings and publication',['../md_docs_2file-lifecycle.html',1,'']]],
  ['and_20rank_20experiment_44',['Collision bitmap and rank experiment',['../collision-bitmap-and-rank-experiment.html',1,'']]],
  ['and_20reservations_45',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['and_20stringlike_20keys_46',['Sorts and stringlike keys',['../md_docs_2keys.html',1,'']]],
  ['and_20the_20bitmap512_20rank_47',['NEON reductions and the Bitmap512 rank',['../md_bench_2neon__bitmap__rank.html',1,'']]],
  ['and_20the_20choice_20of_20k_48',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['arithmetic_20cleanup_49',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['avx2_20packed_20rank_20comparison_50',['Native AVX2 packed-rank comparison',['../native-avx2-packed-rank-comparison.html',1,'']]]
];
