var searchData=
[
  ['cached_20totals_0',['Bounded rank without cached totals',['../bounded-rank-without-cached-totals.html',1,'']]],
  ['catalog_20chain_1',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['catalog_20for_20worlds_20pins_20and_20background_20work_2',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['category_20chosen_20per_20key_3',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['chain_4',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['chain_20queries_5',['Complete prepared-chain queries',['../md_bench_2query__chain.html',1,'']]],
  ['change_6',['Everett: Persistent Storage Through Composable Change',['../index.html',1,'']]],
  ['choice_20of_20k_7',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['chosen_20per_20key_8',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['cleanup_9',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['coding_20with_20comparison_20state_10',['Front coding with comparison state',['../md_docs_2comparison-fc.html',1,'']]],
  ['cold_20exception_20paths_20in_20complete_20queries_11',['Cold exception paths in complete queries',['../cold-exception-paths-in-complete-queries.html',1,'']]],
  ['comparison_12',['comparison',['../md_bench_2rank__compare.html',1,'Full-vector and packed-rank comparison'],['../native-avx2-packed-rank-comparison.html',1,'Native AVX2 packed-rank comparison'],['../md_bench_2rank__compare__windows.html',1,'Native Windows packed-rank comparison']]],
  ['comparison_20state_13',['comparison state',['../md_bench_2query__compare.html',1,'Complete queries with comparison state'],['../md_docs_2comparison-fc.html',1,'Front coding with comparison state']]],
  ['complete_20bitmap_20rank_14',['Stored spacers in complete bitmap rank',['../stored-spacers-in-complete-bitmap-rank.html',1,'']]],
  ['complete_20prepared_20chain_20queries_15',['Complete prepared-chain queries',['../md_bench_2query__chain.html',1,'']]],
  ['complete_20queries_16',['Cold exception paths in complete queries',['../cold-exception-paths-in-complete-queries.html',1,'']]],
  ['complete_20queries_20after_20bit_20arithmetic_20cleanup_17',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['complete_20queries_20after_20the_20rank_20and_20elias–fano_20refactor_18',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['complete_20queries_20with_20comparison_20state_19',['Complete queries with comparison state',['../md_bench_2query__compare.html',1,'']]],
  ['composable_20change_20',['Everett: Persistent Storage Through Composable Change',['../index.html',1,'']]],
  ['construction_21',['Elias–Fano Selection and Construction',['../eliasfano-selection-and-construction.html',1,'']]],
  ['copies_20and_20framing_22',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['core_23',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['count_20decoding_24',['Small bit-profile count decoding',['../md_bench_2small__count.html',1,'']]],
  ['cult_20bitmap_20rank_25',['NEON reductions and the Cult bitmap rank',['../md_bench_2neon__cult__rank.html',1,'']]]
];
