var searchData=
[
  ['cached_20totals_0',['Bounded rank without cached totals',['../bounded-rank-without-cached-totals.html',1,'']]],
  ['carried_20lcps_1',['Index construction with carried LCPs',['../index-construction-with-carried-lcps.html',1,'']]],
  ['carried_20lcps_20in_20cola_20construction_2',['Carried LCPs in COLA construction',['../carried-lcps-in-cola-construction.html',1,'']]],
  ['catalog_20chain_3',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['catalog_20for_20worlds_20pins_20and_20background_20work_4',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['category_20chosen_20per_20key_5',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['chain_6',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['chain_20queries_7',['Complete prepared-chain queries',['../md_bench_2query__chain.html',1,'']]],
  ['chain_20to_20disk_8',['Streaming a fractional-index chain to disk',['../md_docs_2file-indexes.html',1,'']]],
  ['charged_20encoded_20cola_20execution_9',['Charged encoded COLA execution',['../charged-encoded-cola-execution.html',1,'']]],
  ['check_10',['COLA Linux Portability Check',['../cola-linux-portability-check.html',1,'']]],
  ['checked_20alternatives_11',['Temporary collision rank: checked alternatives',['../temporary-collision-rank-checked-alternatives.html',1,'']]],
  ['choice_20of_20k_12',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['choices_13',['Whole-search offset choices',['../whole-search-offset-choices.html',1,'']]],
  ['chosen_20per_20key_14',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['cleanup_15',['cleanup',['../md_bench_2query__rounding.html',1,'Complete queries after bit-arithmetic cleanup'],['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'Conservative tombstones and complete-coverage cleanup']]],
  ['coded_20metal_20merges_16',['Matched fixed-key and front-coded Metal merges',['../matched-fixed-key-and-front-coded-metal-merges.html',1,'']]],
  ['coding_20with_20comparison_20state_17',['Front coding with comparison state',['../md_docs_2comparison-fc.html',1,'']]],
  ['cola_20borrowed_20payload_20sharing_18',['COLA Borrowed Payload Sharing',['../cola-borrowed-payload-sharing.html',1,'']]],
  ['cola_20comparison_20layout_19',['COLA comparison layout',['../cola-comparison-layout.html',1,'']]],
  ['cola_20construction_20',['Carried LCPs in COLA construction',['../carried-lcps-in-cola-construction.html',1,'']]],
  ['cola_20execution_21',['cola execution',['../charged-encoded-cola-execution.html',1,'Charged encoded COLA execution'],['../redundant-cola-execution.html',1,'Redundant COLA execution']]],
  ['cola_20indexes_20and_20mapped_20queries_22',['COLA indexes and mapped queries',['../cola-indexes-and-mapped-queries.html',1,'']]],
  ['cola_20linux_20portability_20check_23',['COLA Linux Portability Check',['../cola-linux-portability-check.html',1,'']]],
  ['cola_20merge_24',['Building a COLA merge',['../building-a-cola-merge.html',1,'']]],
  ['cola_20roots_25',['Saving and merging mapped COLA roots',['../saving-and-merging-mapped-cola-roots.html',1,'']]],
  ['cola_20scheduling_20with_20immutable_20pairs_26',['COLA scheduling with immutable pairs',['../cola-scheduling-with-immutable-pairs.html',1,'']]],
  ['cold_20exception_20paths_20in_20complete_20queries_27',['Cold exception paths in complete queries',['../cold-exception-paths-in-complete-queries.html',1,'']]],
  ['collision_20bitmap_20and_20rank_20experiment_28',['Collision bitmap and rank experiment',['../collision-bitmap-and-rank-experiment.html',1,'']]],
  ['collision_20rank_3a_20checked_20alternatives_29',['Temporary collision rank: checked alternatives',['../temporary-collision-rank-checked-alternatives.html',1,'']]],
  ['compact_20native_20merge_20span_20descriptors_30',['Compact native-merge span descriptors',['../compact-native-merge-span-descriptors.html',1,'']]],
  ['comparison_31',['comparison',['../md_bench_2rank__compare.html',1,'Full-vector and packed-rank comparison'],['../native-avx2-packed-rank-comparison.html',1,'Native AVX2 packed-rank comparison'],['../md_bench_2rank__compare__windows.html',1,'Native Windows packed-rank comparison']]],
  ['comparison_20layout_32',['COLA comparison layout',['../cola-comparison-layout.html',1,'']]],
  ['comparison_20state_33',['comparison state',['../md_bench_2query__compare.html',1,'Complete queries with comparison state'],['../md_docs_2comparison-fc.html',1,'Front coding with comparison state']]],
  ['comparisons_20and_20encoder_20reuse_34',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['complete_20bitmap_20rank_35',['Stored spacers in complete bitmap rank',['../stored-spacers-in-complete-bitmap-rank.html',1,'']]],
  ['complete_20byte_20bit_20file_20space_36',['Complete Byte/Bit File Space',['../complete-bytebit-file-space.html',1,'']]],
  ['complete_20byte_20bit_20space_20results_37',['Complete Byte/Bit Space Results',['../complete-bytebit-space-results.html',1,'']]],
  ['complete_20coverage_20cleanup_38',['Conservative tombstones and complete-coverage cleanup',['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'']]],
  ['complete_20merges_20on_20metal_39',['Fixed-key complete merges on Metal',['../fixed-key-complete-merges-on-metal.html',1,'']]],
  ['complete_20prepared_20chain_20queries_40',['Complete prepared-chain queries',['../md_bench_2query__chain.html',1,'']]],
  ['complete_20queries_41',['Cold exception paths in complete queries',['../cold-exception-paths-in-complete-queries.html',1,'']]],
  ['complete_20queries_20after_20bit_20arithmetic_20cleanup_42',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['complete_20queries_20after_20the_20rank_20and_20elias–fano_20refactor_43',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['complete_20queries_20with_20absolute_20block_20prefixes_44',['Complete queries with absolute block prefixes',['../complete-queries-with-absolute-block-prefixes.html',1,'']]],
  ['complete_20queries_20with_20comparison_20state_45',['Complete queries with comparison state',['../md_bench_2query__compare.html',1,'']]],
  ['complete_20searches_46',['Offset representations in complete searches',['../offset-representations-in-complete-searches.html',1,'']]],
  ['completed_20native_20merges_47',['Reusing completed native merges',['../reusing-completed-native-merges.html',1,'']]],
  ['compressed_20input_20and_20output_48',['Optional GPU merge: direct compressed input and output',['../optional-gpu-merge-direct-compressed-input-and-output.html',1,'']]],
  ['connecting_20to_20a_20named_20session_49',['Connecting to a named session',['../connecting-to-a-named-session.html',1,'']]],
  ['conservative_20tombstones_20and_20complete_20coverage_20cleanup_50',['Conservative tombstones and complete-coverage cleanup',['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'']]],
  ['construction_51',['construction',['../carried-lcps-in-cola-construction.html',1,'Carried LCPs in COLA construction'],['../eliasfano-selection-and-construction.html',1,'Elias–Fano Selection and Construction'],['../one-incoming-key-context-for-index-construction.html',1,'One incoming key context for index construction']]],
  ['construction_20experiment_52',['GPU construction experiment',['../gpu-construction-experiment.html',1,'']]],
  ['construction_20with_20carried_20lcps_53',['Index construction with carried LCPs',['../index-construction-with-carried-lcps.html',1,'']]],
  ['context_20for_20index_20construction_54',['One incoming key context for index construction',['../one-incoming-key-context-for-index-construction.html',1,'']]],
  ['contributions_55',['Typed worlds and contributions',['../typed-worlds-and-contributions.html',1,'']]],
  ['copies_56',['Encoded literals without full-key copies',['../encoded-literals-without-full-key-copies.html',1,'']]],
  ['copies_20and_20framing_57',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['core_58',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['correctness_20qualification_59',['Vulkan correctness qualification',['../vulkan-correctness-qualification.html',1,'']]],
  ['count_20decoding_60',['Small bit-profile count decoding',['../md_bench_2small__count.html',1,'']]],
  ['coverage_20cleanup_61',['Conservative tombstones and complete-coverage cleanup',['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'']]],
  ['cpu_20bit_20and_20byte_20native_20merges_62',['Matched CPU bit and byte native merges',['../matched-cpu-bit-and-byte-native-merges.html',1,'']]],
  ['cpu_20gpu_20cutover_63',['Header-based CPU/GPU cutover',['../header-based-cpugpu-cutover.html',1,'']]],
  ['cpu_20profile_20merges_64',['Matched CPU profile merges',['../matched-cpu-profile-merges.html',1,'']]],
  ['cursor_20advancement_65',['Specializing cursor advancement',['../md_bench_2sample__advance.html',1,'']]],
  ['cutover_66',['cutover',['../header-based-cpugpu-cutover.html',1,'Header-based CPU/GPU cutover'],['../header-only-gpu-cutover.html',1,'Header-only GPU cutover']]]
];
