var searchData=
[
  ['object_20sealing_0',['Immutable object sealing',['../immutable-object-sealing.html',1,'']]],
  ['of_20k_1',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['offset_20choices_2',['Whole-search offset choices',['../whole-search-offset-choices.html',1,'']]],
  ['offset_20directories_3',['Per-file offset directories',['../per-file-offset-directories.html',1,'']]],
  ['offset_20representations_20in_20complete_20searches_4',['Offset representations in complete searches',['../offset-representations-in-complete-searches.html',1,'']]],
  ['offset_20selection_20on_20actual_20file_20directories_5',['Offset selection on actual file directories',['../offset-selection-on-actual-file-directories.html',1,'']]],
  ['offsets_6',['Select alternatives on the same offsets',['../select-alternatives-on-the-same-offsets.html',1,'']]],
  ['on_20actual_20file_20directories_7',['Offset selection on actual file directories',['../offset-selection-on-actual-file-directories.html',1,'']]],
  ['on_20m2_20max_8',['Bit reservoir on M2 Max',['../bit-reservoir-on-m2-max.html',1,'']]],
  ['on_20metal_9',['Fixed-key complete merges on Metal',['../fixed-key-complete-merges-on-metal.html',1,'']]],
  ['on_20the_20same_20offsets_10',['Select alternatives on the same offsets',['../select-alternatives-on-the-same-offsets.html',1,'']]],
  ['one_20incoming_20key_20context_20for_20index_20construction_11',['One incoming key context for index construction',['../one-incoming-key-context-for-index-construction.html',1,'']]],
  ['only_20gpu_20cutover_12',['Header-only GPU cutover',['../header-only-gpu-cutover.html',1,'']]],
  ['optional_20fused_20gpu_20output_20planning_13',['Optional fused GPU output planning',['../optional-fused-gpu-output-planning.html',1,'']]],
  ['optional_20gpu_20merge_3a_20direct_20compressed_20input_20and_20output_14',['Optional GPU merge: direct compressed input and output',['../optional-gpu-merge-direct-compressed-input-and-output.html',1,'']]],
  ['optional_20tiled_20prefix_20tree_20experiment_15',['Optional tiled prefix-tree experiment',['../optional-tiled-prefix-tree-experiment.html',1,'']]],
  ['output_16',['output',['../adaptive-fractional-index-output.html',1,'Adaptive fractional-index output'],['../adaptive-native-and-fractional-index-output.html',1,'Adaptive native and fractional-index output'],['../native-merge-frontiers-and-framed-output.html',1,'Native merge frontiers and framed output'],['../optional-gpu-merge-direct-compressed-input-and-output.html',1,'Optional GPU merge: direct compressed input and output']]],
  ['output_20planning_17',['Optional fused GPU output planning',['../optional-fused-gpu-output-planning.html',1,'']]],
  ['outputs_18',['Small native merge outputs',['../small-native-merge-outputs.html',1,'']]],
  ['owned_20bit_20records_19',['Sort-owned bit records',['../sort-owned-bit-records.html',1,'']]],
  ['owned_20native_20files_20',['Streaming sort-owned native files',['../streaming-sort-owned-native-files.html',1,'']]],
  ['owned_20native_20records_21',['Sort-owned native records',['../sort-owned-native-records.html',1,'']]],
  ['owned_20records_20in_20the_20redundant_20runtime_22',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['ownership_23',['Doxygen metadata and declaration ownership',['../md_docs_2doxygen.html',1,'']]],
  ['owning_20queries_20with_20shared_20navigation_20views_24',['Owning queries with shared navigation views',['../md_bench_2shared__query.html',1,'']]]
];
