var searchData=
[
  ['file_20directories_0',['Offset selection on actual file directories',['../offset-selection-on-actual-file-directories.html',1,'']]],
  ['file_20offset_20directories_1',['Per-file offset directories',['../per-file-offset-directories.html',1,'']]],
  ['file_20space_2',['Complete Byte/Bit File Space',['../complete-bytebit-file-space.html',1,'']]],
  ['files_3',['Streaming sort-owned native files',['../streaming-sort-owned-native-files.html',1,'']]],
  ['files_20mappings_20and_20publication_4',['Files, mappings and publication',['../md_docs_2file-lifecycle.html',1,'']]],
  ['fixed_20key_20and_20front_20coded_20metal_20merges_5',['Matched fixed-key and front-coded Metal merges',['../matched-fixed-key-and-front-coded-metal-merges.html',1,'']]],
  ['fixed_20key_20and_20kv03_20metal_20results_6',['Matched fixed-key and KV03 Metal results',['../matched-fixed-key-and-kv03-metal-results.html',1,'']]],
  ['fixed_20key_20complete_20merges_20on_20metal_7',['Fixed-key complete merges on Metal',['../fixed-key-complete-merges-on-metal.html',1,'']]],
  ['fixed_20key_20merge_20measurements_8',['Fixed-key merge measurements',['../fixed-key-merge-measurements.html',1,'']]],
  ['fixed_20key_20search_9',['Bounded fixed-key search',['../bounded-fixed-key-search.html',1,'']]],
  ['for_20bounded_20512_20bit_20rank_20prefixes_10',['Intel paths for bounded 512-bit rank prefixes',['../intel-paths-for-bounded-512-bit-rank-prefixes.html',1,'']]],
  ['for_20immutable_20worlds_11',['A mutable session for immutable worlds',['../a-mutable-session-for-immutable-worlds.html',1,'']]],
  ['for_20index_20construction_12',['One incoming key context for index construction',['../one-incoming-key-context-for-index-construction.html',1,'']]],
  ['for_20worlds_20pins_20and_20background_20work_13',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['fractional_20index_20chain_20to_20disk_14',['Streaming a fractional-index chain to disk',['../md_docs_2file-indexes.html',1,'']]],
  ['fractional_20index_20output_15',['fractional index output',['../adaptive-fractional-index-output.html',1,'Adaptive fractional-index output'],['../adaptive-native-and-fractional-index-output.html',1,'Adaptive native and fractional-index output']]],
  ['fractional_20indexes_16',['Streaming fractional indexes',['../streaming-fractional-indexes.html',1,'']]],
  ['framed_20output_17',['Native merge frontiers and framed output',['../native-merge-frontiers-and-framed-output.html',1,'']]],
  ['framing_18',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['from_20peers_19',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['front_20coded_20metal_20merges_20',['Matched fixed-key and front-coded Metal merges',['../matched-fixed-key-and-front-coded-metal-merges.html',1,'']]],
  ['front_20coding_20with_20comparison_20state_21',['Front coding with comparison state',['../md_docs_2comparison-fc.html',1,'']]],
  ['frontier_22',['Persisting a runtime frontier',['../persisting-a-runtime-frontier.html',1,'']]],
  ['frontiers_20and_20framed_20output_23',['Native merge frontiers and framed output',['../native-merge-frontiers-and-framed-output.html',1,'']]],
  ['full_20key_20copies_24',['Encoded literals without full-key copies',['../encoded-literals-without-full-key-copies.html',1,'']]],
  ['full_20vector_20and_20packed_20rank_20comparison_25',['Full-vector and packed-rank comparison',['../md_bench_2rank__compare.html',1,'']]],
  ['fused_20gpu_20output_20planning_26',['Optional fused GPU output planning',['../optional-fused-gpu-output-planning.html',1,'']]]
];
