var searchData=
[
  ['range_20aggregates_0',['Column Values and Range Aggregates',['../column-values-and-range-aggregates.html',1,'']]],
  ['rank_1',['rank',['../md_bench_2neon__bitmap__rank.html',1,'NEON reductions and the Bitmap512 rank'],['../stored-spacers-in-complete-bitmap-rank.html',1,'Stored spacers in complete bitmap rank']]],
  ['rank_20and_20elias–fano_20refactor_2',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['rank_20comparison_3',['rank comparison',['../md_bench_2rank__compare.html',1,'Full-vector and packed-rank comparison'],['../native-avx2-packed-rank-comparison.html',1,'Native AVX2 packed-rank comparison'],['../md_bench_2rank__compare__windows.html',1,'Native Windows packed-rank comparison']]],
  ['rank_20experiment_4',['Collision bitmap and rank experiment',['../collision-bitmap-and-rank-experiment.html',1,'']]],
  ['rank_20prefixes_5',['Intel paths for bounded 512-bit rank prefixes',['../intel-paths-for-bounded-512-bit-rank-prefixes.html',1,'']]],
  ['rank_20reductions_6',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['rank_20without_20cached_20totals_7',['Bounded rank without cached totals',['../bounded-rank-without-cached-totals.html',1,'']]],
  ['rank_3a_20checked_20alternatives_8',['Temporary collision rank: checked alternatives',['../temporary-collision-rank-checked-alternatives.html',1,'']]],
  ['reader_20reservoir_20experiment_9',['Bit reader reservoir experiment',['../bit-reader-reservoir-experiment.html',1,'']]],
  ['rebuilding_10',['Strong deletion by incremental rebuilding',['../md_docs_2rebuild.html',1,'']]],
  ['rebuilding_20replacement_20tables_11',['Rebuilding replacement tables',['../rebuilding-replacement-tables.html',1,'']]],
  ['records_12',['records',['../sort-owned-bit-records.html',1,'Sort-owned bit records'],['../sort-owned-native-records.html',1,'Sort-owned native records']]],
  ['records_20in_20the_20redundant_20runtime_13',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['reductions_14',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['reductions_20and_20the_20bitmap512_20rank_15',['NEON reductions and the Bitmap512 rank',['../md_bench_2neon__bitmap__rank.html',1,'']]],
  ['redundant_20cola_20execution_16',['Redundant COLA execution',['../redundant-cola-execution.html',1,'']]],
  ['redundant_20runtime_17',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['refactor_18',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['replacement_20tables_19',['Rebuilding replacement tables',['../rebuilding-replacement-tables.html',1,'']]],
  ['representations_20in_20complete_20searches_20',['Offset representations in complete searches',['../offset-representations-in-complete-searches.html',1,'']]],
  ['reservations_21',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['reservoir_20experiment_22',['Bit reader reservoir experiment',['../bit-reader-reservoir-experiment.html',1,'']]],
  ['reservoir_20on_20m2_20max_23',['Bit reservoir on M2 Max',['../bit-reservoir-on-m2-max.html',1,'']]],
  ['results_24',['results',['../complete-bytebit-space-results.html',1,'Complete Byte/Bit Space Results'],['../matched-fixed-key-and-kv03-metal-results.html',1,'Matched fixed-key and KV03 Metal results']]],
  ['resumption_25',['resumption',['../md_docs_2durability.html',1,'Durable publication and merge resumption'],['../md_docs_2merge-resumption.html',1,'Merge resumption']]],
  ['retained_20select_20measurements_26',['Retained select measurements',['../retained-select-measurements.html',1,'']]],
  ['reuse_27',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['reusing_20borrowed_20key_20prefixes_28',['Reusing borrowed-key prefixes',['../md_bench_2borrowed__prefix.html',1,'']]],
  ['reusing_20completed_20native_20merges_29',['Reusing completed native merges',['../reusing-completed-native-merges.html',1,'']]],
  ['reusing_20native_20key_20prefixes_30',['Reusing native-key prefixes',['../md_bench_2native__prefix.html',1,'']]],
  ['roots_31',['roots',['../mapped-blobs-and-exact-query-roots.html',1,'Mapped blobs and exact query roots'],['../saving-and-merging-mapped-cola-roots.html',1,'Saving and merging mapped COLA roots']]],
  ['roots_20and_20reservations_32',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['runtime_33',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['runtime_20frontier_34',['Persisting a runtime frontier',['../persisting-a-runtime-frontier.html',1,'']]]
];
