var searchData=
[
  ['file_20directories_0',['Offset selection on actual file directories',['../offset-selection-on-actual-file-directories.html',1,'']]],
  ['files_1',['Streaming sort-owned native files',['../streaming-sort-owned-native-files.html',1,'']]],
  ['files_20mappings_20and_20publication_2',['Files, mappings and publication',['../md_docs_2file-lifecycle.html',1,'']]],
  ['fixed_20key_20and_20front_20coded_20metal_20merges_3',['Matched fixed-key and front-coded Metal merges',['../matched-fixed-key-and-front-coded-metal-merges.html',1,'']]],
  ['fixed_20key_20and_20kv03_20metal_20results_4',['Matched fixed-key and KV03 Metal results',['../matched-fixed-key-and-kv03-metal-results.html',1,'']]],
  ['fixed_20key_20complete_20merges_20on_20metal_5',['Fixed-key complete merges on Metal',['../fixed-key-complete-merges-on-metal.html',1,'']]],
  ['fixed_20key_20merge_20measurements_6',['Fixed-key merge measurements',['../fixed-key-merge-measurements.html',1,'']]],
  ['for_20bounded_20512_20bit_20rank_20prefixes_7',['Intel paths for bounded 512-bit rank prefixes',['../intel-paths-for-bounded-512-bit-rank-prefixes.html',1,'']]],
  ['for_20immutable_20worlds_8',['A mutable session for immutable worlds',['../a-mutable-session-for-immutable-worlds.html',1,'']]],
  ['for_20index_20construction_9',['One incoming key context for index construction',['../one-incoming-key-context-for-index-construction.html',1,'']]],
  ['for_20worlds_20pins_20and_20background_20work_10',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['fractional_20index_20chain_20to_20disk_11',['Streaming a fractional-index chain to disk',['../md_docs_2file-indexes.html',1,'']]],
  ['fractional_20index_20output_12',['fractional index output',['../adaptive-fractional-index-output.html',1,'Adaptive fractional-index output'],['../adaptive-native-and-fractional-index-output.html',1,'Adaptive native and fractional-index output']]],
  ['fractional_20indexes_13',['Streaming fractional indexes',['../streaming-fractional-indexes.html',1,'']]],
  ['framed_20output_14',['Native merge frontiers and framed output',['../native-merge-frontiers-and-framed-output.html',1,'']]],
  ['framing_15',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['from_20peers_16',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['front_20coded_20metal_20merges_17',['Matched fixed-key and front-coded Metal merges',['../matched-fixed-key-and-front-coded-metal-merges.html',1,'']]],
  ['front_20coding_20with_20comparison_20state_18',['Front coding with comparison state',['../md_docs_2comparison-fc.html',1,'']]],
  ['frontier_19',['Persisting a runtime frontier',['../persisting-a-runtime-frontier.html',1,'']]],
  ['frontiers_20and_20framed_20output_20',['Native merge frontiers and framed output',['../native-merge-frontiers-and-framed-output.html',1,'']]],
  ['full_20key_20copies_21',['Encoded literals without full-key copies',['../encoded-literals-without-full-key-copies.html',1,'']]],
  ['full_20vector_20and_20packed_20rank_20comparison_22',['Full-vector and packed-rank comparison',['../md_bench_2rank__compare.html',1,'']]],
  ['fused_20gpu_20output_20planning_23',['Optional fused GPU output planning',['../optional-fused-gpu-output-planning.html',1,'']]]
];
