var searchData=
[
  ['sampling_20comparisons_20and_20encoder_20reuse_0',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['sampling_20groups_20and_20the_20choice_20of_20k_1',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['saving_20and_20merging_20mapped_20cola_20roots_2',['Saving and merging mapped COLA roots',['../saving-and-merging-mapped-cola-roots.html',1,'']]],
  ['scanning_20a_20table_3',['Scanning a table',['../scanning-a-table.html',1,'']]],
  ['scheduling_20with_20immutable_20pairs_4',['COLA scheduling with immutable pairs',['../cola-scheduling-with-immutable-pairs.html',1,'']]],
  ['sealing_5',['Immutable object sealing',['../immutable-object-sealing.html',1,'']]],
  ['selection_20and_20construction_6',['Elias–Fano Selection and Construction',['../eliasfano-selection-and-construction.html',1,'']]],
  ['session_7',['Connecting to a named session',['../connecting-to-a-named-session.html',1,'']]],
  ['session_20for_20immutable_20worlds_8',['A mutable session for immutable worlds',['../a-mutable-session-for-immutable-worlds.html',1,'']]],
  ['shader_20toolchain_9',['Everett shader toolchain',['../everett-shader-toolchain.html',1,'']]],
  ['shared_20navigation_20views_10',['Owning queries with shared navigation views',['../md_bench_2shared__query.html',1,'']]],
  ['sharing_11',['COLA Borrowed Payload Sharing',['../cola-borrowed-payload-sharing.html',1,'']]],
  ['small_20bit_20profile_20count_20decoding_12',['Small bit-profile count decoding',['../md_bench_2small__count.html',1,'']]],
  ['small_20native_20merge_20outputs_13',['Small native merge outputs',['../small-native-merge-outputs.html',1,'']]],
  ['sort_20owned_20bit_20records_14',['Sort-owned bit records',['../sort-owned-bit-records.html',1,'']]],
  ['sort_20owned_20native_20files_15',['Streaming sort-owned native files',['../streaming-sort-owned-native-files.html',1,'']]],
  ['sort_20owned_20native_20records_16',['Sort-owned native records',['../sort-owned-native-records.html',1,'']]],
  ['sort_20owned_20records_20in_20the_20redundant_20runtime_17',['Sort-owned records in the redundant runtime',['../sort-owned-records-in-the-redundant-runtime.html',1,'']]],
  ['sorted_20blobs_20from_20peers_18',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['sorts_20and_20stringlike_20keys_19',['Sorts and stringlike keys',['../md_docs_2keys.html',1,'']]],
  ['space_20accounting_20',['Space accounting',['../space-accounting.html',1,'']]],
  ['spacers_20in_20complete_20bitmap_20rank_21',['Stored spacers in complete bitmap rank',['../stored-spacers-in-complete-bitmap-rank.html',1,'']]],
  ['span_20descriptors_22',['Compact native-merge span descriptors',['../compact-native-merge-span-descriptors.html',1,'']]],
  ['specializing_20cursor_20advancement_23',['Specializing cursor advancement',['../md_bench_2sample__advance.html',1,'']]],
  ['sqlite_20catalog_20for_20worlds_20pins_20and_20background_20work_24',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['sqlite_20roots_20and_20reservations_25',['Persistent SQLite roots and reservations',['../md_docs_2sqlite-catalog.html',1,'']]],
  ['state_26',['state',['../md_bench_2query__compare.html',1,'Complete queries with comparison state'],['../md_docs_2comparison-fc.html',1,'Front coding with comparison state']]],
  ['status_27',['Everett implementation status',['../md_docs_2implementation.html',1,'']]],
  ['storage_28',['Everett: Persistent Storage',['../index.html',1,'']]],
  ['stored_20spacers_20in_20complete_20bitmap_20rank_29',['Stored spacers in complete bitmap rank',['../stored-spacers-in-complete-bitmap-rank.html',1,'']]],
  ['streaming_20a_20fractional_20index_20chain_20to_20disk_30',['Streaming a fractional-index chain to disk',['../md_docs_2file-indexes.html',1,'']]],
  ['streaming_20a_20table_20into_20a_20persistent_20timeline_31',['Streaming a table into a persistent timeline',['../md_docs_2streamed-timeline.html',1,'']]],
  ['streaming_20fractional_20indexes_32',['Streaming fractional indexes',['../streaming-fractional-indexes.html',1,'']]],
  ['streaming_20sort_20owned_20native_20files_33',['Streaming sort-owned native files',['../streaming-sort-owned-native-files.html',1,'']]],
  ['string_20tables_34',['Byte String Tables',['../byte-string-tables.html',1,'']]],
  ['stringlike_20keys_35',['Sorts and stringlike keys',['../md_docs_2keys.html',1,'']]],
  ['strong_20deletion_20by_20incremental_20rebuilding_36',['Strong deletion by incremental rebuilding',['../md_docs_2rebuild.html',1,'']]]
];
