var searchData=
[
  ['cached_20totals_0',['Bounded rank without cached totals',['../bounded-rank-without-cached-totals.html',1,'']]],
  ['carried_20lcps_1',['Index construction with carried LCPs',['../index-construction-with-carried-lcps.html',1,'']]],
  ['carried_20lcps_20in_20cola_20construction_2',['Carried LCPs in COLA construction',['../carried-lcps-in-cola-construction.html',1,'']]],
  ['catalog_20chain_3',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['catalog_20for_20worlds_20pins_20and_20background_20work_4',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['category_20chosen_20per_20key_5',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['chain_6',['Querying an immutable catalog chain',['../md_docs_2query.html',1,'']]],
  ['chain_20queries_7',['Complete prepared-chain queries',['../md_bench_2query__chain.html',1,'']]],
  ['chain_20to_20disk_8',['Streaming a fractional-index chain to disk',['../md_docs_2file-indexes.html',1,'']]],
  ['charged_20encoded_20cola_20execution_9',['Charged encoded COLA execution',['../charged-encoded-cola-execution.html',1,'']]],
  ['check_10',['COLA Linux Portability Check',['../cola-linux-portability-check.html',1,'']]],
  ['checked_20alternatives_11',['Temporary collision rank: checked alternatives',['../temporary-collision-rank-checked-alternatives.html',1,'']]],
  ['choice_20of_20k_12',['Sampling groups and the choice of K',['../md_docs_2sampling.html',1,'']]],
  ['chosen_20per_20key_13',['Updates in a category chosen per key',['../md_docs_2arrows.html',1,'']]],
  ['cleanup_14',['cleanup',['../md_bench_2query__rounding.html',1,'Complete queries after bit-arithmetic cleanup'],['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'Conservative tombstones and complete-coverage cleanup']]],
  ['coding_20with_20comparison_20state_15',['Front coding with comparison state',['../md_docs_2comparison-fc.html',1,'']]],
  ['cola_20borrowed_20payload_20sharing_16',['COLA Borrowed Payload Sharing',['../cola-borrowed-payload-sharing.html',1,'']]],
  ['cola_20comparison_20layout_17',['COLA comparison layout',['../cola-comparison-layout.html',1,'']]],
  ['cola_20construction_18',['Carried LCPs in COLA construction',['../carried-lcps-in-cola-construction.html',1,'']]],
  ['cola_20execution_19',['cola execution',['../charged-encoded-cola-execution.html',1,'Charged encoded COLA execution'],['../redundant-cola-execution.html',1,'Redundant COLA execution']]],
  ['cola_20indexes_20and_20mapped_20queries_20',['COLA indexes and mapped queries',['../cola-indexes-and-mapped-queries.html',1,'']]],
  ['cola_20linux_20portability_20check_21',['COLA Linux Portability Check',['../cola-linux-portability-check.html',1,'']]],
  ['cola_20merge_22',['Building a COLA merge',['../building-a-cola-merge.html',1,'']]],
  ['cola_20roots_23',['Saving and merging mapped COLA roots',['../saving-and-merging-mapped-cola-roots.html',1,'']]],
  ['cola_20scheduling_20with_20immutable_20pairs_24',['COLA scheduling with immutable pairs',['../cola-scheduling-with-immutable-pairs.html',1,'']]],
  ['cold_20exception_20paths_20in_20complete_20queries_25',['Cold exception paths in complete queries',['../cold-exception-paths-in-complete-queries.html',1,'']]],
  ['collision_20bitmap_20and_20rank_20experiment_26',['Collision bitmap and rank experiment',['../collision-bitmap-and-rank-experiment.html',1,'']]],
  ['collision_20rank_3a_20checked_20alternatives_27',['Temporary collision rank: checked alternatives',['../temporary-collision-rank-checked-alternatives.html',1,'']]],
  ['compact_20native_20merge_20span_20descriptors_28',['Compact native-merge span descriptors',['../compact-native-merge-span-descriptors.html',1,'']]],
  ['comparison_29',['comparison',['../md_bench_2rank__compare.html',1,'Full-vector and packed-rank comparison'],['../native-avx2-packed-rank-comparison.html',1,'Native AVX2 packed-rank comparison'],['../md_bench_2rank__compare__windows.html',1,'Native Windows packed-rank comparison']]],
  ['comparison_20layout_30',['COLA comparison layout',['../cola-comparison-layout.html',1,'']]],
  ['comparison_20state_31',['comparison state',['../md_bench_2query__compare.html',1,'Complete queries with comparison state'],['../md_docs_2comparison-fc.html',1,'Front coding with comparison state']]],
  ['comparisons_20and_20encoder_20reuse_32',['Sampling comparisons and encoder reuse',['../md_bench_2sample__frontier.html',1,'']]],
  ['complete_20bitmap_20rank_33',['Stored spacers in complete bitmap rank',['../stored-spacers-in-complete-bitmap-rank.html',1,'']]],
  ['complete_20coverage_20cleanup_34',['Conservative tombstones and complete-coverage cleanup',['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'']]],
  ['complete_20merges_20on_20metal_35',['Fixed-key complete merges on Metal',['../fixed-key-complete-merges-on-metal.html',1,'']]],
  ['complete_20prepared_20chain_20queries_36',['Complete prepared-chain queries',['../md_bench_2query__chain.html',1,'']]],
  ['complete_20queries_37',['Cold exception paths in complete queries',['../cold-exception-paths-in-complete-queries.html',1,'']]],
  ['complete_20queries_20after_20bit_20arithmetic_20cleanup_38',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['complete_20queries_20after_20the_20rank_20and_20elias–fano_20refactor_39',['Complete queries after the rank and Elias–Fano refactor',['../complete-queries-after-the-rank-and-eliasfano-refactor.html',1,'']]],
  ['complete_20queries_20with_20absolute_20block_20prefixes_40',['Complete queries with absolute block prefixes',['../complete-queries-with-absolute-block-prefixes.html',1,'']]],
  ['complete_20queries_20with_20comparison_20state_41',['Complete queries with comparison state',['../md_bench_2query__compare.html',1,'']]],
  ['completed_20native_20merges_42',['Reusing completed native merges',['../reusing-completed-native-merges.html',1,'']]],
  ['compressed_20input_20and_20output_43',['Optional GPU merge: direct compressed input and output',['../optional-gpu-merge-direct-compressed-input-and-output.html',1,'']]],
  ['connecting_20to_20a_20named_20session_44',['Connecting to a named session',['../connecting-to-a-named-session.html',1,'']]],
  ['conservative_20tombstones_20and_20complete_20coverage_20cleanup_45',['Conservative tombstones and complete-coverage cleanup',['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'']]],
  ['construction_46',['construction',['../carried-lcps-in-cola-construction.html',1,'Carried LCPs in COLA construction'],['../eliasfano-selection-and-construction.html',1,'Elias–Fano Selection and Construction'],['../one-incoming-key-context-for-index-construction.html',1,'One incoming key context for index construction']]],
  ['construction_20experiment_47',['GPU construction experiment',['../gpu-construction-experiment.html',1,'']]],
  ['construction_20with_20carried_20lcps_48',['Index construction with carried LCPs',['../index-construction-with-carried-lcps.html',1,'']]],
  ['context_20for_20index_20construction_49',['One incoming key context for index construction',['../one-incoming-key-context-for-index-construction.html',1,'']]],
  ['contributions_50',['Typed worlds and contributions',['../typed-worlds-and-contributions.html',1,'']]],
  ['copies_51',['Encoded literals without full-key copies',['../encoded-literals-without-full-key-copies.html',1,'']]],
  ['copies_20and_20framing_52',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['core_53',['Everett: An Abstract Proof Core',['../everett-an-abstract-proof-core.html',1,'']]],
  ['correctness_20qualification_54',['Vulkan correctness qualification',['../vulkan-correctness-qualification.html',1,'']]],
  ['count_20decoding_55',['Small bit-profile count decoding',['../md_bench_2small__count.html',1,'']]],
  ['coverage_20cleanup_56',['Conservative tombstones and complete-coverage cleanup',['../conservative-tombstones-and-complete-coverage-cleanup.html',1,'']]],
  ['cpu_20gpu_20cutover_57',['Header-based CPU/GPU cutover',['../header-based-cpugpu-cutover.html',1,'']]],
  ['cursor_20advancement_58',['Specializing cursor advancement',['../md_bench_2sample__advance.html',1,'']]],
  ['cutover_59',['cutover',['../header-based-cpugpu-cutover.html',1,'Header-based CPU/GPU cutover'],['../header-only-gpu-cutover.html',1,'Header-only GPU cutover']]]
];
