var searchData=
[
  ['background_20work_0',['SQLite catalog for worlds, pins and background work',['../md_docs_2catalog.html',1,'']]],
  ['based_20cpu_20gpu_20cutover_1',['Header-based CPU/GPU cutover',['../header-based-cpugpu-cutover.html',1,'']]],
  ['benchmark_20evidence_2',['Benchmark evidence',['../benchmark-evidence.html',1,'']]],
  ['bit_20and_20byte_20native_20merges_3',['Matched CPU bit and byte native merges',['../matched-cpu-bit-and-byte-native-merges.html',1,'']]],
  ['bit_20arithmetic_20cleanup_4',['Complete queries after bit-arithmetic cleanup',['../md_bench_2query__rounding.html',1,'']]],
  ['bit_20copies_20and_20framing_5',['Key prefixes, bit copies, and framing',['../md_bench_2key__bits.html',1,'']]],
  ['bit_20profile_20count_20decoding_6',['Small bit-profile count decoding',['../md_bench_2small__count.html',1,'']]],
  ['bit_20rank_20prefixes_7',['Intel paths for bounded 512-bit rank prefixes',['../intel-paths-for-bounded-512-bit-rank-prefixes.html',1,'']]],
  ['bit_20records_8',['Sort-owned bit records',['../sort-owned-bit-records.html',1,'']]],
  ['bitmap_20and_20rank_20experiment_9',['Collision bitmap and rank experiment',['../collision-bitmap-and-rank-experiment.html',1,'']]],
  ['bitmap_20rank_10',['Stored spacers in complete bitmap rank',['../stored-spacers-in-complete-bitmap-rank.html',1,'']]],
  ['bitmap_20rank_20reductions_11',['Packed group and bitmap rank reductions',['../packed-group-and-bitmap-rank-reductions.html',1,'']]],
  ['bitmap512_20rank_12',['NEON reductions and the Bitmap512 rank',['../md_bench_2neon__bitmap__rank.html',1,'']]],
  ['blob_20and_20pipeline_20performance_13',['Blob and pipeline performance',['../blob-and-pipeline-performance.html',1,'']]],
  ['blobs_20and_20exact_20query_20roots_14',['Mapped blobs and exact query roots',['../mapped-blobs-and-exact-query-roots.html',1,'']]],
  ['blobs_20from_20peers_15',['Admitting sorted blobs from peers',['../md_docs_2network-admission.html',1,'']]],
  ['block_20prefixes_16',['Complete queries with absolute block prefixes',['../complete-queries-with-absolute-block-prefixes.html',1,'']]],
  ['borrowed_20key_20prefixes_17',['Reusing borrowed-key prefixes',['../md_bench_2borrowed__prefix.html',1,'']]],
  ['borrowed_20payload_20sharing_18',['COLA Borrowed Payload Sharing',['../cola-borrowed-payload-sharing.html',1,'']]],
  ['bounded_20512_20bit_20rank_20prefixes_19',['Intel paths for bounded 512-bit rank prefixes',['../intel-paths-for-bounded-512-bit-rank-prefixes.html',1,'']]],
  ['bounded_20rank_20without_20cached_20totals_20',['Bounded rank without cached totals',['../bounded-rank-without-cached-totals.html',1,'']]],
  ['building_20a_20cola_20merge_21',['Building a COLA merge',['../building-a-cola-merge.html',1,'']]],
  ['by_20incremental_20rebuilding_22',['Strong deletion by incremental rebuilding',['../md_docs_2rebuild.html',1,'']]],
  ['byte_20native_20merges_23',['Matched CPU bit and byte native merges',['../matched-cpu-bit-and-byte-native-merges.html',1,'']]],
  ['byte_20string_20tables_24',['Byte String Tables',['../byte-string-tables.html',1,'']]]
];
