var searchData=
[
  ['m2_20max_0',['Bit reservoir on M2 Max',['../bit-reservoir-on-m2-max.html',1,'']]],
  ['mapped_20blobs_20and_20exact_20query_20roots_1',['Mapped blobs and exact query roots',['../mapped-blobs-and-exact-query-roots.html',1,'']]],
  ['mapped_20cola_20roots_2',['Saving and merging mapped COLA roots',['../saving-and-merging-mapped-cola-roots.html',1,'']]],
  ['mapped_20queries_3',['COLA indexes and mapped queries',['../cola-indexes-and-mapped-queries.html',1,'']]],
  ['mappings_20and_20publication_4',['Files, mappings and publication',['../md_docs_2file-lifecycle.html',1,'']]],
  ['matched_20byte_20and_20bit_20lookups_5',['Matched byte and bit lookups',['../matched-byte-and-bit-lookups.html',1,'']]],
  ['matched_20cpu_20bit_20and_20byte_20native_20merges_6',['Matched CPU bit and byte native merges',['../matched-cpu-bit-and-byte-native-merges.html',1,'']]],
  ['matched_20cpu_20profile_20merges_7',['Matched CPU profile merges',['../matched-cpu-profile-merges.html',1,'']]],
  ['matched_20fixed_20key_20and_20front_20coded_20metal_20merges_8',['Matched fixed-key and front-coded Metal merges',['../matched-fixed-key-and-front-coded-metal-merges.html',1,'']]],
  ['matched_20fixed_20key_20and_20kv03_20metal_20results_9',['Matched fixed-key and KV03 Metal results',['../matched-fixed-key-and-kv03-metal-results.html',1,'']]],
  ['max_10',['Bit reservoir on M2 Max',['../bit-reservoir-on-m2-max.html',1,'']]],
  ['measurements_11',['measurements',['../byte-profile-metal-merge-measurements.html',1,'Byte-profile Metal merge measurements'],['../fixed-key-merge-measurements.html',1,'Fixed-key merge measurements'],['../retained-select-measurements.html',1,'Retained select measurements']]],
  ['merge_12',['merge',['../building-a-cola-merge.html',1,'Building a COLA merge'],['../byte-profile-gpu-merge.html',1,'Byte-profile GPU merge']]],
  ['merge_20frontiers_20and_20framed_20output_13',['Native merge frontiers and framed output',['../native-merge-frontiers-and-framed-output.html',1,'']]],
  ['merge_20measurements_14',['merge measurements',['../byte-profile-metal-merge-measurements.html',1,'Byte-profile Metal merge measurements'],['../fixed-key-merge-measurements.html',1,'Fixed-key merge measurements']]],
  ['merge_20outputs_15',['Small native merge outputs',['../small-native-merge-outputs.html',1,'']]],
  ['merge_20resumption_16',['merge resumption',['../md_docs_2durability.html',1,'Durable publication and merge resumption'],['../md_docs_2merge-resumption.html',1,'Merge resumption']]],
  ['merge_20span_20descriptors_17',['Compact native-merge span descriptors',['../compact-native-merge-span-descriptors.html',1,'']]],
  ['merge_3a_20direct_20compressed_20input_20and_20output_18',['Optional GPU merge: direct compressed input and output',['../optional-gpu-merge-direct-compressed-input-and-output.html',1,'']]],
  ['merges_19',['merges',['../matched-cpu-bit-and-byte-native-merges.html',1,'Matched CPU bit and byte native merges'],['../matched-cpu-profile-merges.html',1,'Matched CPU profile merges'],['../matched-fixed-key-and-front-coded-metal-merges.html',1,'Matched fixed-key and front-coded Metal merges'],['../reusing-completed-native-merges.html',1,'Reusing completed native merges']]],
  ['merges_20on_20metal_20',['Fixed-key complete merges on Metal',['../fixed-key-complete-merges-on-metal.html',1,'']]],
  ['merging_21',['Incremental native writing and merging',['../md_docs_2native-merges.html',1,'']]],
  ['merging_20mapped_20cola_20roots_22',['Saving and merging mapped COLA roots',['../saving-and-merging-mapped-cola-roots.html',1,'']]],
  ['metadata_20and_20declaration_20ownership_23',['Doxygen metadata and declaration ownership',['../md_docs_2doxygen.html',1,'']]],
  ['metal_24',['Fixed-key complete merges on Metal',['../fixed-key-complete-merges-on-metal.html',1,'']]],
  ['metal_20merge_20measurements_25',['Byte-profile Metal merge measurements',['../byte-profile-metal-merge-measurements.html',1,'']]],
  ['metal_20merges_26',['Matched fixed-key and front-coded Metal merges',['../matched-fixed-key-and-front-coded-metal-merges.html',1,'']]],
  ['metal_20results_27',['Matched fixed-key and KV03 Metal results',['../matched-fixed-key-and-kv03-metal-results.html',1,'']]],
  ['mit_28',['LICENSE.MIT',['../licensemit.html',1,'']]],
  ['mutable_20session_20for_20immutable_20worlds_29',['A mutable session for immutable worlds',['../a-mutable-session-for-immutable-worlds.html',1,'']]]
];
