#!/usr/bin/env python3
# \file
# \author Edward Kmett <ekmett@gmail.com>
# \brief Compiles one HLSL entry to validated SPIR-V and optional Metal.
#
# SPDX-FileCopyrightText: 2026 Edward Kmett <ekmett@gmail.com>
# SPDX-License-Identifier: BSD-2-Clause OR Apache-2.0
"""Everett shader toolchain: validated SPIR-V, optional Metal and reflected bindings."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
import time


RESOURCE_KINDS = {
    "push_constants": "buffer",
    "ubos": "buffer",
    "ssbos": "buffer",
    "images": "texture",
    "separate_images": "texture",
    "storage_images": "texture",
    "separate_samplers": "sampler",
}

def run(command):
    subprocess.run([str(value) for value in command], check=True)


def temporary_output(path):
    descriptor, name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    os.close(descriptor)
    return Path(name)


def acquire_output_lock(output):
    # Separate recursive build invocations can race the same deterministic
    # recipe. Keep coordination metadata outside declared shader outputs so
    # artifact packaging cannot accidentally include lock files.
    identity = hashlib.sha256(str(output.resolve()).encode()).hexdigest()
    owner = str(os.getuid()) if hasattr(os, "getuid") else "windows"
    directory = Path(tempfile.gettempdir()) / f"everett-shader-locks-{owner}"
    directory.mkdir(parents=True, exist_ok=True)
    lock = open(directory / f"{identity}.lock", "a+b")
    if os.name == "nt":
        import msvcrt

        lock.seek(0, os.SEEK_END)
        if lock.tell() == 0:
            lock.write(b"\0")
            lock.flush()
        lock.seek(0)
        msvcrt.locking(lock.fileno(), msvcrt.LK_LOCK, 1)
    else:
        import fcntl

        fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
    return lock


def release_output_lock(lock):
    if os.name == "nt":
        import msvcrt

        lock.seek(0)
        msvcrt.locking(lock.fileno(), msvcrt.LK_UNLCK, 1)
    else:
        import fcntl

        fcntl.flock(lock.fileno(), fcntl.LOCK_UN)
    lock.close()


def reflect(spirv_cross, spv):
    return json.loads(
        subprocess.check_output([str(spirv_cross), str(spv), "--reflect"], text=True)
    )


def binding_header(reflection, source, prefix, namespace):
    constants = []
    seen = set()
    # SPIRV-Cross maps the one Vulkan push-constant block to Metal buffer(0).
    for resource in reflection.get("push_constants", []):
        key = ("buffer", resource["name"])
        seen.add(key)
        constants.append(
            f"inline constexpr unsigned {prefix}_{resource['name']}_buffer_binding = 0;"
        )
    for category, kind in RESOURCE_KINDS.items():
        for resource in reflection.get(category, []):
            name = resource["name"]
            # DXC gives constant-buffer blocks a synthetic `type.` prefix.
            # It is compiler metadata rather than part of the source resource name.
            if name.startswith("type."):
                name = name.removeprefix("type.")
            name = re.sub(r"[^A-Za-z0-9_]", "_", name)
            key = (kind, name)
            if key in seen:
                continue
            seen.add(key)
            binding = resource.get("binding", 0)
            constants.append(
                f"inline constexpr unsigned {prefix}_{name}_{kind}_binding = "
                f"{binding};"
            )
    lines = [
        "#pragma once",
        f"// Reflected from {Path(source).name}; generated by shader_compile.py.",
    ]
    if namespace:
        lines.append(f"namespace {namespace} {{")
        lines.extend(f"  {constant}" for constant in constants)
        lines.append(f"}} // namespace {namespace}")
    else:
        lines.extend(constants)
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--entry", required=True)
    parser.add_argument("--output-entry")
    parser.add_argument("--msl-entry")
    parser.add_argument("--profile", default="cs_6_0")
    parser.add_argument("--enable-16bit-types", action="store_true")
    parser.add_argument("--vulkan-memory-model", action="store_true")
    parser.add_argument("--invert-y", action="store_true")
    parser.add_argument("--spv", type=Path, required=True)
    parser.add_argument("--msl", type=Path)
    parser.add_argument("--bindings", type=Path)
    parser.add_argument("--msl-texture-buffer-native", action="store_true")
    parser.add_argument("--msl-auto-bindings", action="store_true")
    parser.add_argument("--binding-prefix")
    parser.add_argument("--namespace", default="everett_gpu")
    parser.add_argument("--define", action="append", default=[])
    parser.add_argument("--include", type=Path, action="append", default=[])
    parser.add_argument("--target", default="vulkan1.3")
    parser.add_argument("--dxc", default="dxc")
    parser.add_argument("--spirv-val", default="spirv-val")
    parser.add_argument("--spirv-cross", default="spirv-cross")
    args = parser.parse_args()

    requested_outputs = tuple(
        output for output in (args.spv, args.msl, args.bindings) if output
    )
    for output in requested_outputs:
        if output:
            output.parent.mkdir(parents=True, exist_ok=True)
    started = time.time_ns()
    output_lock = acquire_output_lock(args.spv)
    if all(
        output.exists() and output.stat().st_mtime_ns >= started
        for output in requested_outputs
    ):
        release_output_lock(output_lock)
        return
    temporary = {output: temporary_output(output) for output in requested_outputs}
    temporary_spv = temporary[args.spv]
    command = [
        args.dxc,
        "-spirv",
        "-HV",
        "2021",
        "-fvk-use-scalar-layout",
        f"-fspv-target-env={args.target}",
        "-T",
        args.profile,
        "-E",
        args.entry,
    ]
    if args.enable_16bit_types:
        command.append("-enable-16bit-types")
    if args.vulkan_memory_model:
        command.append("-fspv-use-vulkan-memory-model")
    if args.invert_y:
        command.append("-fvk-invert-y")
    if args.output_entry:
        command.append(f"-fspv-entrypoint-name={args.output_entry}")
    command.extend(f"-D{define}" for define in args.define)
    # DXC can treat mixed separators as different include identities on Windows,
    # bypassing #pragma once. Match the forward slashes in HLSL include names;
    # do not rewrite arbitrary arguments such as macro values or entry names.
    command.extend(f"-I{include.as_posix()}" for include in args.include)
    command.extend([args.source.as_posix(), "-Fo", temporary_spv.as_posix()])
    try:
        run(command)
        # DXC is invoked with -fvk-use-scalar-layout above. Buffer-device-address
        # structs expose that layout to validation even when descriptor-backed
        # shaders happen not to need the explicit validator feature switch.
        run(
            [
                args.spirv_val,
                "--target-env",
                args.target,
                "--scalar-block-layout",
                temporary_spv,
            ]
        )

        reflection = None
        if args.bindings or args.msl:
            reflection = reflect(args.spirv_cross, temporary_spv)
        if args.bindings:
            prefix = args.binding_prefix or args.entry
            temporary[args.bindings].write_text(
                binding_header(reflection, args.source, prefix, args.namespace)
            )
        if args.msl:
            metal_command = [
                args.spirv_cross,
                temporary_spv,
                "--msl",
                "--msl-version",
                "30200",
            ]
            if not args.msl_auto_bindings:
                metal_command.append("--msl-decoration-binding")
            if args.msl_texture_buffer_native:
                metal_command.append("--msl-texture-buffer-native")
            if args.msl_entry:
                entry_name = args.output_entry or args.entry
                entries = [entry for entry in reflection["entryPoints"]
                           if entry["name"] == entry_name]
                if len(entries) != 1:
                    raise ValueError(f"Expected one SPIR-V entry named {entry_name!r}")
                metal_command.extend(
                    [
                        "--rename-entry-point",
                        entry_name,
                        args.msl_entry,
                        entries[0]["mode"],
                    ]
                )
            metal_command.extend(["--output", temporary[args.msl]])
            run(metal_command)

        # Compile and validate every requested artifact before publishing any.
        # Each replacement is atomic; multiple artifacts are not a filesystem
        # transaction. An OS error still fails the build and requires a retry.
        for output in requested_outputs:
            os.replace(temporary[output], output)
    finally:
        for output in requested_outputs:
            temporary[output].unlink(missing_ok=True)
        release_output_lock(output_lock)


if __name__ == "__main__":
    main()
